stack-of-tasks/pinocchio

CMakeLists.txt
src/tools/matrix-comparison.hpp
unittest/cholesky.cpp
unittest/com.cpp
unittest/compute-all-terms.cpp
unittest/constraint.cpp
unittest/crba.cpp
unittest/fusion.cpp
unittest/jacobian.cpp
unittest/joints.cpp
unittest/non-linear-effects.cpp
unittest/rnea.cpp
unittest/symmetric.cpp
unittest/tspatial.cpp
unittest/udut.cpp
unittest/urdf.cpp
unittest/value.cpp
unittest/variant.cpp

Complete switch from raw asserts to BOOST_TEST_SUITE as unittest framework.

[Major][Unittest] Unifying unittest framework with boost_test_suite

---

src/python/algorithms.hpp
src/python/model.hpp

Added two minor functionalities in the python bindings. Possibly double check with Justin that the modifiction in algorithms.hpp is not too bad.
Nico

Minor adds to python

---

src/python/algorithms.hpp

It might be a good idea to add a build test for this case on Travis.

[Python][Build] Fix compile error in case hpp-fcl is not used.

---

doc/Doxyfile.extra.in
doc/additionalDoc/crtp.hh
doc/additionalDoc/loading.hh
doc/additionalDoc/package.hh

This pull request initiates a documentation using Doxygen. It contains
- a main page introducing the main features of the library,
- related pages providing more advanced information.
TODO:
complete the page "Loading a model" to enable users to build models from urdf/srdf files.

Start documentation using doxygen.

---

src/python/geometry-data.hpp
src/python/geometry-model.hpp
src/python/parsers.hpp
src/python/robot_wrapper.py

Change API to load robot from urdf file. Only the number of arguments matters.

Use same name to load urdf model with or without root joint

---

src/multibody/geometry.hpp
src/multibody/geometry.hxx
src/python/geometry-data.hpp
src/python/robot_wrapper.py

A dedicated unit test is coming soon.

Handle SRDF file parsing for activation of collision pairs

---

src/python/inertia.hpp
src/spatial/inertia.hpp
unittest/tspatial.cpp

Same as #120 , revised following @jcarpent comments.

Inertia.From{Ellipsoid,Cylinder,Box}

---

src/multibody/model.hpp
src/multibody/model.hxx
travis_custom/custom_before_install

The Geometry part will be soon tested on Travis as soon as the last hpp-fcl release is available on robotpkg.

Improve doc of Model+Data and add python bindings in Travis

---

.travis.yml
lab/python/exp_integration.py
lab/python/kineinv.py
python/bindings.py
python/test_model.py
src/python/__init__.py
src/python/explog.py
src/python/robot_wrapper.py
src/python/romeo_wrapper.py
src/python/rpy.py
src/python/utils.py

Here are three commits. Each one could have been one PR, but this is mainly for discussions.
The first one is about reformatting most python file to comply a little more with some main indications stated in [pep8](https://www.python.org/dev/peps/pep-0008/)
The second makes python tests work again
The third tells to Travis to run those tests.
I will probably change a bit how those tests are implemented, and then work on coverage, if you find this useful.

[Python] Some propositions about Format & Tests

---

CMakeLists.txt
src/algorithm/cholesky.hpp
src/algorithm/cholesky.hxx
src/algorithm/dynamics.hpp
src/multibody/model.hpp
src/multibody/model.hxx
src/python/algorithms.hpp
src/python/data.hpp
src/spatial/se3.hpp
unittest/CMakeLists.txt
unittest/dynamics.cpp

This new feature allows to handle the forward dynamics with contacts problem. The current version exploits the sparsity of the model, but it does not handle the conic friction cone, neither the LCP formulation of contact.
@nmansard One question remains: must Pinocchio provide some contact algorithms or do you need to create a dedicated project ?

Add forward dynamics with contacts algorithm 

---

python/utils.py
src/python/utils.py

Not sure if this PR is really useful, but it looks like we had some broken code…

[Python] fix ViewerConfigurationToXYZQUAT

---

.travis.yml
src/multibody/joint/joint-free-flyer.hpp
src/multibody/joint/joint-spherical.hpp
unittest/constraint.cpp
unittest/joint-configurations.cpp

Rework joint free flyer and joint spherical to avoid useless allocations

---

.gitignore
src/algorithm/aba.hxx
src/algorithm/center-of-mass.hxx
src/algorithm/crba.hxx
src/algorithm/jacobian.hxx
src/algorithm/kinematics.hxx
src/algorithm/rnea.hxx
src/math/quaternion.hpp
src/multibody/joint/joint-base.hpp
src/multibody/joint/joint-dense.hpp
src/multibody/joint/joint-free-flyer.hpp
src/multibody/joint/joint-planar.hpp
src/multibody/joint/joint-prismatic-unaligned.hpp
src/multibody/joint/joint-prismatic.hpp
src/multibody/joint/joint-revolute-unaligned.hpp
src/multibody/joint/joint-revolute.hpp
src/multibody/joint/joint-spherical-ZYX.hpp
src/multibody/joint/joint-spherical.hpp
src/multibody/joint/joint-translation.hpp
src/multibody/model.cpp
src/multibody/model.hxx
src/python/joint-dense.hpp
unittest/joint-configurations.cpp

In particular, the joints are fully converted in their dense version.
The algorithms do not rely on joint index directly.

Rework joints and algo

---

python/bindings_SE3.py
python/bindings_force.py
python/bindings_frame.py
python/bindings_geometry_object.py
python/bindings_inertia.py
python/bindings_motion.py
python/tests.py
src/algorithm/operational-frames.hpp
src/multibody/model.hxx
src/python/frame.hpp
src/spatial/frame.hpp

Added some python tests to check that spatial classes are well exposed in python.
Modified some exposition of class member ( through .def_readwrite instead of .add_attribute for aligned datas).
+ minor correction of the names of Frame members

Python exposure tests

---

CMakeLists.txt
src/CMakeLists.txt

Allow the user to not compile the python binding if unnecessary

Add a cmake variable to choose if the pyhton wrapper will be compile or not

---

unittest/geom.cpp

Fix call to old API

---

index.html

Sorry for the fast previous PR, can be good to wait for another typos check on monday before merging...

Fix link to Download page

---

src/multibody/model.hpp
src/python/robot_wrapper.py

Fix missing of geometry modules

---

src/algorithm/joint-configuration.hpp
src/multibody/joint/joint-base.hpp
src/multibody/joint/joint-basic-visitors.hpp
src/multibody/joint/joint-basic-visitors.hxx
src/multibody/joint/joint-dense.hpp
src/multibody/joint/joint-free-flyer.hpp
src/multibody/joint/joint-spherical.hpp
src/multibody/joint/joint.hpp
unittest/joint-configurations.cpp

Solves #239 and related to https://github.com/humanoid-path-planner/hpp-pinocchio/issues/14

Add se3::normalized

---

CMakeLists.txt

At least, tests & my code runs well without urdfdom :)

[CMake] urdfdom is optional

---

.travis.yml

Make coverage and cppcheck optional and dependant of the current branch

---

python/bindings_frame.py
python/bindings_geometry_object.py

[Python] Updating Python tests to corresponds to the API 

---

unittest/joint.cpp

Some tests were using== operator instead of isApprox

[unittest] Fixed precision comparison test.

---

src/multibody/joint/joint-variant.hpp
src/multibody/joint/joint.hpp

This PR solved the bug mentioned in #231. Whoopee !!!

Handle 32 bits system

---

bindings/python/robot_wrapper.py
src/algorithm/geometry.hpp
src/algorithm/geometry.hxx
src/multibody/fcl.hpp
src/multibody/fcl.hxx
src/multibody/fwd.hpp
src/multibody/geometry.hpp
src/multibody/geometry.hxx
src/parsers/urdf.hpp
src/parsers/urdf/geometry.cpp
unittest/geom.cpp

Refactorize geometry module

---

benchmark/timings-geometry.cpp
benchmark/timings.cpp
src/multibody/joint/joint-prismatic-unaligned.hpp
src/multibody/joint/joint-revolute-unaligned.hpp
src/multibody/model.hpp
src/multibody/model.hxx
src/parsers/urdf.hpp
unittest/urdf.cpp

removing deprecated methods + change unaligned joints with boost fusion fix

---

src/multibody/constraint.hpp
src/multibody/joint/joint-composite.hpp

New JointComposite was not aligned on 32 bits arch.

Fix alignment issue for the JointComposite

---

src/multibody/model.hpp
src/multibody/model.hxx
src/parsers/sample-models.cpp
src/parsers/urdf/model.cpp
unittest/joint-configurations.cpp
unittest/visitor.cpp

Remove default name for joint

---

src/multibody/joint/joint-free-flyer.hpp
src/multibody/joint/joint-spherical.hpp

Change assert accuracy to 1e-4 in forwardKinematics

---

.travis.yml
CMakeLists.txt
travis_custom/custom_build

This option is set by default to ON.

Set installation of documentation as an option

---

bindings/python/algorithm/expose-aba.cpp
bindings/python/algorithm/expose-com.cpp
bindings/python/algorithm/expose-crba.cpp
bindings/python/algorithm/expose-dynamics.cpp
bindings/python/algorithm/expose-energy.cpp
bindings/python/algorithm/expose-frames.cpp
bindings/python/algorithm/expose-geometry.cpp
bindings/python/algorithm/expose-jacobian.cpp
bindings/python/algorithm/expose-joints.cpp
bindings/python/algorithm/expose-kinematics.cpp
bindings/python/algorithm/expose-rnea.cpp

This PR also solves a bug in the normalize function.

Clean Python bindings by removing useless proxy

---

bindings/python/multibody/joint/joint.hpp
bindings/python/multibody/model.hpp
bindings/python/scripts/robot_wrapper.py
src/algorithm/frames.hpp
src/algorithm/kinematics.hpp
src/algorithm/kinematics.hxx
src/multibody/model.hxx
src/spatial/fcl-pinocchio-conversions.hpp
src/spatial/se3.hpp

This PR solves several bug in the Python bindings and a minimal algo to update the global placement of the joints according to the relative placements contained in data.

Multiple fixes

---

bindings/python/multibody/geometry-object.hpp
bindings/python/scripts/robot_wrapper.py
src/multibody/fcl.hpp
src/multibody/fcl.hxx
src/parsers/urdf/geometry.cpp
unittest/geom.cpp

*add `meshScale` to `GeometryObject`
*change `GeometryObject` constructor

[Geometry] [Viewer] add scaling parameter to GeometryObject.

---

src/multibody/joint/joint-planar.hpp
src/spatial/explog.hpp
unittest/geom.cpp
unittest/joint-configurations.cpp
unittest/joints.cpp

The python bindings do not compile. The error is:
```
fatal error: pinocchio/parsers/python.hpp: No such file or directory
```
I guess it is suppose to find `bindings/python/parsers/python.hpp`...

Planar joint uses cosine and sine of the angle.

---

src/parsers/urdf/model.cpp

* When not set, the limits are set to infinity.
However, the case of unbounded and unaligned revolute joint is not covered.

[Minor][C++] URDF parser uses JointModelRevoluteUnbounded for continuous

---

bindings/python/scripts/robot_wrapper.py

* addMesh returns boolean in new gepetto-viewer API. Proceed only if addMesh is True

[Python] Fix robot_wrapper binding

---

bindings/python/scripts/robot_wrapper.py
lab/inverse-kinematics
src/algorithm/rnea.hpp

[Minor][Spelling] biais in english is bias.

---

bindings/python/multibody/geometry-object.hpp
bindings/python/scripts/robot_wrapper.py
src/multibody/fcl.hpp
src/multibody/geometry.hxx
src/parsers/urdf/geometry.cpp

Takes into account the definition of material in a urdf link
*save texture and color information in geometryModel
If (material is defined):
* update the viewer in robot_wrapper

[C++][Visual] Save "Material" information in geometry object

---

bindings/python/CMakeLists.txt
bindings/python/algorithm/expose-jacobian.cpp
bindings/python/module.cpp
bindings/python/multibody/fcl/collision-geometry.hpp
bindings/python/multibody/fcl/collision-result.hpp
bindings/python/multibody/fcl/contact.hpp
bindings/python/multibody/fcl/expose-fcl.cpp
bindings/python/multibody/geometry-data.hpp
bindings/python/multibody/geometry-model.hpp
bindings/python/multibody/geometry-object.hpp
bindings/python/scripts/robot_wrapper.py
bindings/python/spatial/se3.hpp
src/multibody/liegroup/cartesian-product.hpp
src/multibody/liegroup/operation-base.hpp
src/multibody/liegroup/vector-space.hpp
src/spatial/se3.hpp
unittest/tspatial.cpp

Expose FCL objects + fix some minor bugs

---

src/parsers/urdf/geometry.cpp
src/parsers/urdf/model.cpp

Fix bug when using std::shared_ptr

---

bindings/python/CMakeLists.txt

Handle FCL exposition if hpp-fcl is not found

---

src/multibody/model.hpp
src/parsers/urdf/model.cpp
unittest/urdf.cpp

Useful when one does not known which robot will be loaded.

Add name to model and set it when loading a urdf file.

---

src/algorithm/frames.hpp
unittest/frames.cpp

Update algo to avoid unnecessary computations + fix potential bugs

Correct frameJacobians

---

doc/Doxyfile.extra.in
src/algorithm/finite-differences.hxx
src/multibody/liegroup/cartesian-product.hpp
src/multibody/liegroup/operation-base.hpp
src/multibody/liegroup/operation-base.hxx
src/multibody/liegroup/special-euclidean.hpp
src/multibody/liegroup/special-orthogonal.hpp
src/multibody/liegroup/vector-space.hpp
unittest/liegroups.cpp

neutral returns the neutral element as an eigen vector.
A unit test has been added.

Add methods "name" and "neutral" in OperationBase and derived classes

---

src/CMakeLists.txt
src/parsers/srdf.cpp
src/parsers/srdf.hpp
src/parsers/urdf.hpp
src/parsers/urdf/geometry.cpp
src/parsers/urdf/model.cpp
src/parsers/urdf/types.hpp

* in order to build model from XML string (standard in ROS)

Add overload of buildModel and buildGeom

---

bindings/python/multibody/geometry-object.hpp
unittest/crba.cpp

Fix bug related to HPP-FCL

---

bindings/python/scripts/robot_wrapper.py

Currently only joint accelerations are supported

[bindings][robot_wrapper]  add frameAcceleration to robot_wrapper.

---

models/simple_humanoid.urdf
src/parsers/urdf.hpp
src/parsers/urdf/geometry.cpp
unittest/urdf.cpp

Handle capsules and cylinders in a cleaner way.

---

CMakeLists.txt
bindings/python/algorithm/expose-frames.cpp
bindings/python/algorithm/expose-jacobian.cpp
bindings/python/module.cpp
bindings/python/scripts/robot_wrapper.py
src/algorithm/frames.hpp
src/algorithm/frames.hxx
src/algorithm/jacobian.hpp
src/algorithm/jacobian.hxx
src/multibody/fwd.hpp
unittest/aba.cpp
unittest/dynamics.cpp
unittest/finite-differences.cpp
unittest/frames.cpp
unittest/jacobian.cpp
unittest/joints.cpp

This PR fixes the issues related to #418:
- removes the template parameter from getFrameJacobians (it now returns the Jacobian of a given Frame expressed in this frame)
- introduces the notion of LOCAL and WORLD frame

Fix issues related to #418

---

CMakeLists.txt
bindings/python/CMakeLists.txt
bindings/python/algorithm/algorithms.hpp
bindings/python/algorithm/expose-regressor.cpp
src/algorithm/regressor.hpp
src/algorithm/regressor.hxx
src/multibody/model.hpp
src/multibody/model.hxx
unittest/CMakeLists.txt
unittest/regressor.cpp

@andreadelprete @thomasfla 
I've just implemented the static regressor that links the total system CoM to the links' inertial parameters

Add static regressor

---

bindings/python/scripts/robot_wrapper.py

Solves https://github.com/stack-of-tasks/pinocchio/issues/438

[Python] Fix RobotWrapper constructor when package_dirs is None

---

README.md
bindings/python/parsers/parsers.hpp
src/parsers/urdf.hpp
src/parsers/urdf/model.cpp
unittest/urdf.cpp

link to #444.
@cmastalli It might be interesting for you.

Handle XML stream inside URDF parsers

---

_includes/doc/install-linux.md
_includes/doc/install-robotpkg.md

Hi,
Pinocchio is now in the main robotpkg repository, and has been split in two packages.
This commit updates the installation instructions accordingly.

update install instructions

---

bindings/python/algorithm/expose-joints.cpp
bindings/python/scripts/deprecated.py
src/algorithm/joint-configuration.hpp
src/algorithm/joint-configuration.hxx
src/multibody/liegroup/liegroup-algo.hxx
unittest/joint-configurations.cpp
unittest/liegroups.cpp

Differentiate was not the right term as it is devoded to differential calculus.
This is related to #432.

Change differentiate into difference

---

src/parsers/sample-models.cpp

Minor modifs, mostly to make the documentation simpler.

[parser] Minor modifications in sample humanoid

---

src/spatial/force-dense.hpp
src/spatial/motion-dense.hpp

Motion.setRandom() and Force.setRandom() were setting to zero instead of random

[spatial] fixed bug in random force and motion

---

bindings/python/CMakeLists.txt
bindings/python/parsers/expose-parsers.cpp
bindings/python/parsers/sample-models.hpp
src/parsers/sample-models.cpp
src/parsers/sample-models.hpp
unittest/CMakeLists.txt
unittest/sample-models.cpp

Add sample manipulator and humanoid models, with kinematic tree and geometries.
Add python bindings for the two models (4 functions)
Add unittest.

[parser] Add two sample models 

---

benchmark/timings-cholesky.cpp
benchmark/timings-derivatives.cpp
benchmark/timings.cpp
src/parsers/sample-models.cpp
unittest/aba-derivatives.cpp
unittest/aba.cpp
unittest/algo-check.cpp
unittest/centroidal.cpp
unittest/cholesky.cpp
unittest/com.cpp
unittest/compute-all-terms.cpp
unittest/crba.cpp
unittest/dynamics.cpp
unittest/energy.cpp
unittest/finite-differences.cpp
unittest/frames.cpp
unittest/jacobian.cpp
unittest/kinematics-derivatives.cpp
unittest/model.cpp
unittest/regressor.cpp
unittest/rnea-derivatives.cpp
unittest/rnea.cpp
unittest/sample-models.cpp

This PR removes the warning recently introduced in #554.

Remove warnings

---

bindings/python/parsers/sample-models.hpp
src/parsers/sample-models.cpp
src/parsers/sample-models.hpp
unittest/frames.cpp
unittest/sample-models.cpp

Fix compatibility when HPP-FCL is missing

---

src/math/taylor-expansion.hpp
src/spatial/explog.hpp

Handle precision for Taylor expansions according to the scalar type

---

CMakeLists.txt
src/deprecated-macros.hpp

Follows discussions in PR #586

deprecation: change handling of deprecated macros

---

bindings/python/algorithm/expose-joints.cpp
bindings/python/scripts/deprecated.py
bindings/python/scripts/explog.py
bindings/python/spatial/explog.hpp
bindings/python/spatial/expose-explog.cpp

Add exposure of:
- neutral algorithm
- Jlog3, Jexp3, Jlog6, and Jexp6

Update Python bindings

---

doc/_porting.md
doc/treeview.dox

Hi,
I think it's time to make some porting notes.
Following a talk with @nmansard, I included them in the doc.
I just put the first few things that came to my mind. If anybody can think of anything else to add (especially @jcarpent), they can add here.
I preferred to make this PR to the devel branch, rather than topic/doc-v2, because this way it will be immediately available.

[doc] Porting notes to 2.0

---

src/algorithm/center-of-mass.hxx
src/algorithm/joint-configuration.hxx
src/algorithm/kinematics-derivatives.hxx
src/multibody/liegroup/liegroup-algo.hxx

Fix recent boost version issue

---

src/multibody/joint/joint-basic-visitors.hxx

Related to discussions in #511.

all: fix additional bug related to recent versions of boost

---

doc/b-examples/i-inverse-kinematics.md
examples/i-inverse-kinematics.cpp
examples/i-inverse-kinematics.py

I have slightly modified the example and code (changed termination condition) and added comments.

[doc] Inverse kinematics worked example

---

.gitmodules

Thanks to @nim65s for pointing this issue.

submodules: use relative url

---

bindings/python/multibody/data.hpp

[minor] change name of StdVec_Matrix6x raised by @gabrielebndn in #682

---

src/multibody/joint/joint-free-flyer.hpp
src/multibody/joint/joint-spherical.hpp
unittest/kinematics.cpp

joints: fix calc with static constructor

---

src/algorithm/jacobian.hxx
src/algorithm/joint-configuration.hxx
unittest/jacobian.cpp

Finally, I found the bugs related to #674 after some hard times.
@nim65s Can you confirm everything goes fine now?

Fix 18.04 bugs

---

doc/b-examples/i-inverse-kinematics.md
examples/i-inverse-kinematics.cpp
examples/i-inverse-kinematics.py

Following #673, the inverse kinematics example needed some changes. I fixed it

[examples] Fix i-inverse-kinematics

---

bindings/python/utils/dependencies.cpp
doc/treeview.dox
src/math/quaternion.hpp

[doc] [bindings] Small fixes to doxygen and Python bindings

---

bindings/python/pinocchio/utils.py
doc/d-practical-exercises/1-directgeom.md
doc/d-practical-exercises/src/display.py
doc/d-practical-exercises/src/mobilerobot.py
doc/d-practical-exercises/src/ocp.py
doc/d-practical-exercises/src/pendulum.py
doc/d-practical-exercises/src/prm_display.py
doc/d-practical-exercises/src/robot_hand.py
doc/d-practical-exercises/src/ur5x4.py
models/simple_model.py
unittest/python/utils.py

Fix doc issues related to new gepetto-viewer API modifications

---

src/math/fwd.hpp

Thanks to @jmirabel for pointing this warning.

math: remove unused PId variable

---

src/parsers/urdf/geometry.hxx

[parsers/urdf] Add inline to member function retrieveCollisionGeometry

---

src/parsers/urdf/geometry.hxx

Fix issue when hpp-fcl is missing

---

unittest/srdf.cpp

This was causing bugs in DEBUG mode

unittest/srdf: fix vector size

---

bindings/python/multibody/model.hpp
bindings/python/serialization/serializable.hpp

python/serialization: change header inclusions

---

bindings/python/multibody/data.hpp
src/algorithm/aba-derivatives.hxx
src/algorithm/rnea-derivatives.hxx
src/multibody/data.hpp
src/multibody/data.hxx
src/multibody/model.hxx
unittest/aba-derivatives.cpp
unittest/rnea-derivatives.cpp

Derivatives algorithms are now all coherent with respect to the kinematics derivatives

---

bindings/python/pinocchio/robot_wrapper.py
src/algorithm/rnea.hxx

Minor fixes

---

.travis.yml
src/algorithm/model.hxx
src/multibody/fcl.hpp
src/multibody/fcl.hxx
src/parsers/urdf/geometry.hxx
unittest/model.cpp

Fix issue related HPP-FCL support

---

bindings/python/CMakeLists.txt

cmake: fix hpp-fcl support

---

bindings/python/algorithm/expose-centroidal.cpp
bindings/python/multibody/data.hpp

1) Expose data.h
2) Expose computeCentroidalDynamics
3) small simplification in computation of v in computecentroidaldynamics.

Minor changes in repository

---

src/algorithm/joint-configuration.hpp

Fix https://github.com/stack-of-tasks/pinocchio/issues/759
Add some mathematical insight to the documentation of ```integrate```, ```difference``` and ```dIntegrate```.

Add documentation for dIntegrate function.

---

bindings/python/spatial/se3.hpp
src/spatial/se3-tpl.hpp

As per title. Also, I removed a duplicate exposed default constructor

[bindings] Expose SE3 constructor from homogeneous matrix

---

src/multibody/liegroup/special-orthogonal.hpp

#776 made me look at this and realize the error.

Fix first order normalization of unit complex.

---

doc/a-features/e-lie.md

[Minor][Doc] Minor fix of SE(2) overview.

---

unittest/sincos.cpp

Fixes https://github.com/stack-of-tasks/pinocchio/issues/796

Added some tolerance in testSINCOS()

---

.travis.yml
src/math/sincos.hpp

math/sincos: improve the genericity of the sincos methods

---

src/algorithm/regressor.hxx

Completes #818 by addressing the last comments
On my machine (Ubuntu 16.04), the following test
```
#include <pinocchio/algorithm/regressor.hpp>
#include <iostream>
int main (int argc, char *argv[]) 
{ 
using namespace pinocchio;
Motion v;
Motion a;
Data::BodyRegressorType res;
for(int i=0; i<10000000; i++) {
v.setRandom();
a.setRandom();
bodyRegressor(v,a,res);
}
return 0;
} 
```
is about 40% faster with the new version
Old:
New:

[algorithm] [regressor] Minor improvements

---

src/algorithm/frames.hxx
unittest/casadi-algo.cpp

Improve the compatibility with CasADi

---

CMakeLists.txt

Following the suggestion in #827

turn OFF BUILD_UNIT_TESTS by default

---

bindings/python/algorithm/expose-com.cpp
src/algorithm/center-of-mass.hpp
src/algorithm/center-of-mass.hxx
src/multibody/model.hxx
unittest/com.cpp
unittest/model.cpp

Fix and improve #841: add subtree Jacobian

---

bindings/python/algorithm/expose-cholesky.cpp
src/algorithm/cholesky.hpp
src/algorithm/cholesky.hxx
unittest/cholesky.cpp

fix computeMinv from the Cholesky decomposition

---

src/algorithm/model.hxx
unittest/model.cpp

Add assertion in appendModel

---

examples/overview-urdf.py
examples/python/gepetto-viewer.py
examples/python/load-urdf.py
examples/python/meshcat-viewer.py
examples/python/robot-wrapper-viewer.py

I was running the examples to check out the recent `pinocchio` `conda-forge` package and bumped into a few minor issues.

Python 2/3 compatibility of examples.

---

doc/header.html

[Doc] Fix link to MathJax.

---

doc/d-practical-exercises/1-directgeom.md

Hi,
This fix a few mistakes, and update this tutorial to the new API in several places.
I think we have a newer tutorial somewhere, but can't find it… @nmansard could you send me that link back ?

[Doc] update practical exercise 1

---

src/algorithm/regressor.hxx

Fix issue related to #885

---

src/algorithm/frames.hxx

algo/frames: add missing typedef

---

benchmark/timings-cg.cpp
src/codegen/code-generator-base.hpp
src/multibody/joint/joint-common-operations.hpp

cg: add missing include

---

.travis.yml

This will use package.xml when git describe failed.

cmake: sync submodule

---

bindings/python/pinocchio/robot_wrapper.py
bindings/python/pinocchio/visualize/base_visualizer.py

Following a remark by @nmansard

[python] [RobotWrapper] [visualize] Add rebuildData

---

README.md

C++98 and 03 are currently supported

doc: fix list of supported C++ versions

---

bindings/python/algorithm/expose-centroidal.cpp
bindings/python/pinocchio/deprecated.py
src/algorithm/centroidal.hpp
src/algorithm/centroidal.hxx
src/macros.hpp
unittest/centroidal-derivatives.cpp
unittest/centroidal.cpp

Following discussions in #939.

Rename centroidal functions and add new signatures

---

bindings/python/algorithm/expose-joints.cpp
src/algorithm/joint-configuration.hpp
src/algorithm/joint-configuration.hxx
src/multibody/liegroup/cartesian-product.hpp
src/multibody/liegroup/liegroup-algo.hxx
src/multibody/liegroup/liegroup-base.hpp
src/multibody/liegroup/liegroup-base.hxx
src/multibody/liegroup/special-orthogonal.hpp
unittest/joint-configurations.cpp

Related to #949. @cmastalli This PR is for you.

Add dDifference function

---

src/multibody/model.hxx

Fix potential bug when dividing

Init to Ones the rotorGearRatio vector

---

src/multibody/data.hxx
unittest/data.cpp

@Leph I've fixed your issue ;)

Fix constructor for Data, related to #970

---

bindings/python/pinocchio/__init__.py
bindings/python/pinocchio/shortcuts.py
bindings/python/utils/dependencies.cpp
unittest/python/bindings_geometry_object.py

@jmirabel This PR fixes the issues revealed in #979.

python: fix naming of the variable

---

bindings/python/pinocchio/rpy.py

The bug appeared when using gepetto-gui

Fix bug in function nptotuple when called with an array 

---

bindings/python/multibody/geometry-data.hpp
bindings/python/multibody/geometry-model.hpp
bindings/python/multibody/geometry-object.hpp
bindings/python/multibody/model.hpp
bindings/python/pinocchio/deprecated.py
src/algorithm/geometry.hxx
src/multibody/fcl.hpp
src/multibody/fcl.hxx
src/multibody/geometry.hpp
src/multibody/geometry.hxx
src/parsers/urdf/geometry.hxx
unittest/urdf.cpp

@jmirabel Can you check if the change I did are fine with you?

Fix Geometry module

---

bindings/python/algorithm/expose-model.cpp
bindings/python/parsers/parsers.hpp
bindings/python/utils/list.hpp
src/algorithm/model.hpp
src/algorithm/model.hxx
src/multibody/data.hpp
src/multibody/data.hxx
src/multibody/model.hpp
src/multibody/model.hxx

Add new signatures and make more robust the Python bindings.

Improve algos on Models

---

bindings/python/algorithm/expose-model.cpp
bindings/python/multibody/geometry-model.hpp
src/algorithm/model.hpp
src/algorithm/model.hxx
src/multibody/fcl.hpp
src/multibody/geometry.hpp
unittest/model.cpp

Solves #976 
@nmansard This is for you.

Add new signatures for buildReducedModel with geometries

---

examples/CMakeLists.txt
examples/collisions.cpp
examples/collisions.py
src/algorithm/geometry.hpp
src/algorithm/geometry.hxx
src/parsers/srdf.hpp
src/parsers/srdf.hxx

Related to #1008.
@ Linjackffy This PR is for you.

Add C++ example for collision

---

bindings/python/algorithm/expose-frames.cpp
src/algorithm/frames.hpp
src/algorithm/frames.hxx
src/algorithm/jacobian.hxx
src/multibody/model.hpp
unittest/frames.cpp

Add computeFrameJacobian with reference_frame as input arg

---

src/multibody/model.hpp
unittest/model.cpp
unittest/spatial.cpp

And fixes a bug in Model::operator==

Improve coverage

---

src/serialization/eigen.hpp

Thanks to @aelkazdadi for raising the issue.

Fix bug when compiling with C++11

---

benchmark/timings-cg.cpp
src/codegen/code-generator-algo.hpp
src/codegen/code-generator-base.hpp
unittest/cppad-algo-derivatives.cpp
unittest/cppad-algo.cpp
unittest/cppadcg-algo.cpp

1) A set of minor fixes for the benchmark of code-gen.
2) Spell check on code-gen

Minor fixes in code-gen benchmark and code-gen

---

doc/Doxyfile.extra.in

Fixes #1069. Alternative to #1070

[doc] [practical exercises] Fix file links

---

examples/display-shapes.py

Fix print of error message in Python

---

src/parsers/urdf/model.hxx

[URDF][Minor] Add missing typedef.

---

bindings/python/algorithm/expose-centroidal.cpp
bindings/python/pinocchio/robot_wrapper.py
src/algorithm/centroidal.hpp

Extend RobotWrapper methods

---

bindings/python/pinocchio/__init__.py
bindings/python/pinocchio/shortcuts.py

otherwise, `verbose = True` generates:
```python
AttributeError: 'module' object has no attribute 'WITH_HPP_FCL_BINDINGS'
```

[Python] Fix usage of WITH_HPP_FCL_BINDINGS

---

unittest/joints.cpp

fix unittest bug with Eigen version 3.3

---

unittest/quaternion.cpp

Related to https://github.com/stack-of-tasks/pinocchio/issues/1146

[test] test quaternion::uniformRandom

---

src/parsers/urdf/types.hpp

Fix typo in URDF parsers

---

examples/panda3d-viewer-play.py
examples/panda3d-viewer.py

Fix of the fix of panda3d_viewer examples

---

bindings/python/module.cpp
bindings/python/multibody/geometry-data.hpp
bindings/python/utils/deprecation.hpp
src/algorithm/geometry.hxx
src/multibody/geometry.hpp
src/multibody/geometry.hxx

…-> distanceRequests
Together with https://github.com/humanoid-path-planner/hpp-fcl/pull/169, this enables to use the GJK initial guess by default.

[Geometry] collisionRequest -> collisionRequests and distanceRequest -> distanceRequests

---

src/algorithm/frames.hpp
src/algorithm/frames.hxx
src/algorithm/jacobian.hxx
unittest/frames.cpp

Solve #1205. 
@grizzi This PR fixes the issue you mentioned so far. How do you install Pinoccho on your side?

Handle LOCAL_WOLRD_ALIGNED in frames algorithms

---

package.xml

package.xml: Add dependency on catkin/ament_cmake for packaging

---

doc/b-examples/o-reduced-model.md
examples/CMakeLists.txt
examples/build-reduced-model.py

Related to #1232 .
@jcarpent @olivier-stasse This is for you.

Add python example and doc for buildReducedModel

---

bindings/python/algorithm/algorithms.hpp
bindings/python/algorithm/expose-algorithms.cpp
bindings/python/algorithm/expose-frames-derivatives.cpp
bindings/python/algorithm/expose-kinematics-derivatives.cpp
src/algorithm/frames-derivatives.hpp
src/algorithm/frames-derivatives.hxx
src/algorithm/jacobian.hxx
src/algorithm/kinematics-derivatives.hpp
src/algorithm/kinematics-derivatives.hxx
unittest/CMakeLists.txt
unittest/frames-derivatives.cpp
unittest/kinematics-derivatives.cpp

@cmastalli This should help you.

Add support for LOCAL_WORLD_ALIGNED in kinematics derivatives

---

doc/Doxyfile.extra.in
doc/d-practical-exercises/7-learn.md

Fix documentation

---

src/algorithm/aba-derivatives.hxx
src/algorithm/aba.hxx
src/algorithm/center-of-mass-derivatives.hxx
src/algorithm/center-of-mass.hxx
src/algorithm/centroidal-derivatives.hxx
src/algorithm/centroidal.hxx
src/algorithm/cholesky.hxx
src/algorithm/compute-all-terms.hpp
src/algorithm/contact-dynamics.hxx
src/algorithm/crba.hxx
src/algorithm/frames-derivatives.hxx
src/algorithm/frames.hxx
src/algorithm/jacobian.hxx
src/algorithm/joint-configuration.hxx
src/algorithm/kinematics-derivatives.hxx
src/algorithm/kinematics.hxx
src/algorithm/model.hxx
src/algorithm/regressor.hxx
src/algorithm/rnea-derivatives.hxx
src/algorithm/rnea.hxx
src/macros.hpp

Add helper macro PINOCCHIO_CHECK_ARGUMENT_SIZE

---

bindings/python/algorithm/expose-com.cpp
bindings/python/module.cpp
src/algorithm/center-of-mass.hpp
src/algorithm/center-of-mass.hxx
src/algorithm/copy.hpp
src/multibody/fwd.hpp
unittest/python/bindings_com.py

Add additional semantic KinematicLevel

---

bindings/python/multibody/joint/expose-joints.cpp
bindings/python/multibody/joint/joint-derived.hpp
bindings/python/multibody/joint/joints-variant.hpp
bindings/python/multibody/model.hpp
src/algorithm/model.hxx
src/multibody/model.hpp
src/multibody/model.hxx
src/parsers/urdf/model.cpp
src/parsers/urdf/model.hxx
src/serialization/model.hpp

Related to #1291. Currently, the values are not yet exploited in dynamics algorithms.

Add support of joint friction and dampings

---

bindings/python/algorithm/expose-rnea.cpp
src/algorithm/aba-derivatives.hxx
src/algorithm/rnea-derivatives.hxx
src/algorithm/rnea.hpp
src/algorithm/rnea.hxx
src/multibody/data.hpp
src/multibody/data.hxx
src/multibody/joint/joint-spherical.hpp
src/serialization/data.hpp
unittest/rnea-derivatives.cpp
unittest/rnea.cpp

Avoid the recomputation of intermediate quantities.

Add getCoriolisMatrix

---

src/algorithm/dynamics.hpp

add missing use of PINOCCHIO_PRAGMA_DEPRECATED_HEADER

---

bindings/python/algorithm/expose-contact-dynamics.cpp
src/algorithm/contact-dynamics.hpp
src/algorithm/contact-dynamics.hxx
unittest/contact-dynamics.cpp
unittest/python/bindings_dynamics.py

Related to #1326.
@mayataka, this is for you.

Add computeKKTContactDynamicMatrixInverse

---

bindings/python/pinocchio/visualize/gepetto_visualizer.py

One more boring minor commit, sorry x)

gepetto visualizer: explicit error message if GV is not installed

---

src/algorithm/aba.hpp
src/algorithm/aba.hxx

[aba] Use data.a_gf instead of data.a

---

bindings/python/algorithm/expose-cat.cpp
bindings/python/algorithm/expose-crba.cpp
bindings/python/algorithm/expose-kinematics-derivatives.cpp
src/algorithm/center-of-mass-derivatives.hpp
src/algorithm/center-of-mass-derivatives.hxx
src/algorithm/centroidal.hxx
src/algorithm/compute-all-terms.hpp
src/algorithm/compute-all-terms.hxx
src/algorithm/crba.hxx
src/multibody/data.hpp
unittest/center-of-mass-derivatives.cpp
unittest/compute-all-terms.cpp
unittest/joint-revolute.cpp
unittest/python/bindings_com_velocity_derivatives.py

Add computation of centroidal quantities in computeAllTerms

---

src/spatial/explog.hpp

Follows https://github.com/stack-of-tasks/pinocchio/pull/1385

[Doc] Add remarkable identities for Jlog6

---

src/spatial/explog.hpp

[Doc] Fix doc of Jlog6

---

bindings/python/algorithm/expose-aba-derivatives.cpp
bindings/python/algorithm/expose-rnea-derivatives.cpp

Improve doc

---

bindings/python/multibody/frame.hpp
src/multibody/frame.hpp
src/multibody/model.hpp
src/multibody/model.hxx
src/parsers/urdf/model.hxx
src/serialization/frame.hpp
src/spatial/inertia.hpp
src/spatial/symmetric3.hpp

Add Inertia info to Frame

---

src/serialization/vector.hpp

Fix missing include

---

bindings/python/serialization/serializable.hpp
bindings/python/serialization/serialization.cpp
bindings/python/serialization/serialization.hpp
src/serialization/archive.hpp
src/serialization/serializable.hpp
src/serialization/static-buffer.hpp
unittest/serialization.cpp

This is code is pushed here but subject to API change

Enhance serialization 

---

src/parsers/urdf/model.hxx
unittest/urdf.cpp

+ revert commit made to debug the issue.

Fix bug in urdf parsing (win32+debug)

---

.github/workflows/macos-linux-conda.yml
CMakeLists.txt
bindings/python/math/expose-rpy.cpp
bindings/python/spatial/expose-skew.cpp
src/container/boost-container-limits.hpp

Enforce BOOST_MPL_LIMIT_LIST_SIZE

---

src/algorithm/model.hxx
src/multibody/joint/joint-generic.hpp
src/serialization/vector.hpp

Fix bug for Boost 1.58

---

bindings/python/pinocchio/visualize/meshcat_visualizer.py
src/algorithm/centroidal-derivatives.hxx
src/parsers/urdf/geometry.hxx
unittest/centroidal-derivatives.cpp

Fix bug in Centroidal derivatives

---

.github/workflows/ros-ci.yml

ci: update ROS CI

---

README.md
bindings/python/CMakeLists.txt
bindings/python/pinocchio/visualize/__init__.py
bindings/python/pinocchio/visualize/rviz_visualizer.py
examples/README.md
examples/rviz-viewer.py
examples/sample-model-viewer.py

Basic implementation to use RViz as visualizer.

Add RVizVisualizer

---

doc/d-practical-exercises/src/robot_hand.py

https://github.com/stack-of-tasks/pinocchio/issues/1481.
Thank you for providing the source code. I hope this code will work correctly

fix reshape issues

---

bindings/python/pinocchio/visualize/rviz_visualizer.py

Changes are : 
* Give the option to the user to not init a ros node in **initViewer** (if one is already started) to prevent a crash
* Re-implement **clean** method to actually follow spec
* So small bug fix

RVizVisualizer update

---

README.md

Add list of projects based on Pinocchio

---

src/algorithm/contact-dynamics.hpp

Fix constrained dynamics formula

---

src/algorithm/aba.hxx
unittest/algo-check.cpp

Fix bug in ABAChecker

---

bindings/python/pinocchio/robot_wrapper.py

For your information, @jcarpent 
Close #1605

allow `robot_wrapper` to share data with its `viz`

---

bindings/python/algorithm/expose-model.cpp
src/algorithm/model.hxx

Fix bug in appendModel

---

src/multibody/liegroup/liegroup-base.hpp

Related to https://github.com/stack-of-tasks/pinocchio/issues/1752#issuecomment-1260773339

Add @note to difference documentation

---

examples/CMakeLists.txt
unittest/python/pybind11/CMakeLists.txt

Enhance cmake packaging

---

bindings/python/spatial/force.hpp
bindings/python/spatial/inertia.hpp
bindings/python/spatial/motion.hpp
bindings/python/spatial/se3.hpp

Fix issue with clang

---

src/algorithm/regressor.hpp

- this is currently causing a compile error when using clang

regressor: change position of PINOCCHIO_DEPRECATED

---

bindings/python/pinocchio/utils.py

Fix Python issues

---

bindings/python/multibody/geometry-object.hpp

Fix registration of ptr to Python

---

src/spatial/explog.hpp

This PR proposes some extra documentation to fully-define `Jlog6`.

Documentation for Jlog6

---

unittest/frames.cpp

to fix build with -DBUILD_WITH_URDF_SUPPORT=OFF

remove useless header

---

unittest/python/bindings_SE3.py
unittest/python/bindings_force.py
unittest/python/bindings_inertia.py
unittest/python/bindings_motion.py

Enforce testing of Python bindings

---

bindings/python/spatial/force.hpp
bindings/python/spatial/inertia.hpp
bindings/python/spatial/motion.hpp
bindings/python/spatial/se3.hpp

@duburcqa Could you check this fix on your side?

Fix issue with Python 3.6

---

src/spatial/explog.hpp

Fix Jlog6 documentation

---

bindings/python/pybind11-all.hpp

This PR includes pybind11 support for spatial forces.
It would be nice if you guys can make a conda release with these bits.

Support force in pybind11

---

.github/workflows/ros-ci.yml
examples/CMakeLists.txt
examples/static-contact-dynamics.py

This PR adds a new python example. The example computes the static contact dynamics with Solo12.

add static-contact-dynamics example

---

doc/b-examples/f-update-model.md
examples/update-model-after-urdf.py

Related to the following discussions:
- https://github.com/stack-of-tasks/pinocchio/issues/1334
- https://github.com/stack-of-tasks/pinocchio/discussions/1910

Python example: update joint placements after loading a URDF

---

src/multibody/frame.hpp

Closes https://github.com/stack-of-tasks/pinocchio/issues/1928

Define operational frames in the documentation

---

bindings/python/spatial/motion.hpp
src/multibody/joint/joint-planar.hpp
src/multibody/joint/joint-prismatic-unaligned.hpp
src/multibody/joint/joint-prismatic.hpp
src/multibody/joint/joint-revolute-unaligned.hpp
src/multibody/joint/joint-revolute.hpp
src/multibody/joint/joint-spherical.hpp
src/multibody/joint/joint-translation.hpp
src/spatial/force-ref.hpp
src/spatial/motion-base.hpp
src/spatial/motion-dense.hpp
src/spatial/motion-ref.hpp
src/spatial/motion-tpl.hpp
src/spatial/motion-zero.hpp
src/spatial/motion.hpp

Closes https://github.com/stack-of-tasks/pinocchio/issues/1945

Add Motion::toHomogeneousMatrix

---

doc/b-examples/f-update-model.md
doc/pinocchio_cheat_sheet.tex
src/parsers/urdf/geometry.cpp
src/parsers/utils.hpp

Correct "a URDF" (not "an URDF", the prononciation of 'U' as a letter is /ˌju/).

The insatiable English teacher PR 🧙

---

doc/b-examples/d-inverse-kinematics.md
examples/inverse-kinematics.cpp
examples/inverse-kinematics.py

This correction makes sure the error is in the local frame (previously in target frame).
Note that it reverts https://github.com/stack-of-tasks/pinocchio/pull/1875 which was not the correct fix to the convergence issue. Now we are back to the original target and the IK example converges correctly.
See https://github.com/stack-of-tasks/pinocchio/issues/1959#issuecomment-1543725756

Fix IK example in the documentation

---

.github/workflows/ros-ci.yml
CHANGELOG.md
include/pinocchio/algorithm/centroidal.hxx
include/pinocchio/algorithm/compute-all-terms.hxx
unittest/centroidal.cpp

Fix missing term for centroidal dynamics derivatives

---

CHANGELOG.md
include/pinocchio/multibody/fwd.hpp

Following https://github.com/stack-of-tasks/pinocchio/discussions/2183, the definition of the Jacobian is not very clear.
I propose to improve it.

[doc] Improve documentation of ReferenceFrame.

---

doc/c-maths/b-joints.md

Context: https://github.com/stack-of-tasks/pinocchio/discussions/2184#discussioncomment-9046849

Document configuration vector for the planar joint

---

CHANGELOG.md
include/pinocchio/autodiff/casadi-algo.hpp
unittest/casadi/aba.cpp

Adds helper functions to get CasADi function's operation count.

Add get operation counts for Casadi

---

CHANGELOG.md
bindings/python/pinocchio/visualize/meshcat_visualizer.py

solves #2291, I tried @jcarpent's commit locally on my machine and meshes are again properly displayed.

Fix mesh visualization in meshcat

---

CHANGELOG.md
examples/anymal-simulation.py

Running the code raises an ArgumentError. Robot's model (robot.model) has not passed to pinocchio.RigidConstraintModel function.

Argument missing in anymal-simulation.py

---

.github/workflows/linux.yml

This pr aims at adding ubuntu 24.04 support in the linux CI.

CI - Added support for ubuntu 24.04

---

.github/workflows/conda/environment_macos_linux.yml
.github/workflows/conda/environment_windows.yml
.github/workflows/macos-linux-conda.yml
.github/workflows/scripts/get_label.js
.github/workflows/windows-conda.yml

This pr aims at providing cmake compilations options based on the labels from pull requests. When no label are added, a minimal setup is provided. 
For more informations, please see https://github.com/stack-of-tasks/pinocchio/issues/2251

CI - Compilation options based on pull request labels

---

src/CMakeLists.txt

This is mainly necessary when use cmake generator features

Add core headers to target library

---

CHANGELOG.md
include/pinocchio/parsers/meshloader-fwd.hpp
include/pinocchio/parsers/sdf/geometry.hxx
include/pinocchio/parsers/urdf.hpp
sources.cmake

Hi,
This enable compatibility with https://github.com/lmontaut/hpp-fcl/pull/1, while not breaking anything with hpp-fcl v2.4.4

non-breaking coal initial compatibility

---

.github/workflows/check_label.yml

This pr fixes the workflow that checks label when a pr is created.

CI - Fix automatic comment

---

doc/a-features/intro.md

These ??? where left out in #2351.

doc - Correct ??? placeholder.

---

include/pinocchio/bindings/python/context/casadi.hpp

Solves https://github.com/stack-of-tasks/pinocchio/issues/2349

Fix compatibility with NumPy 2.x

---

CHANGELOG.md
bindings/python/parsers/mjcf/model.cpp
src/parsers/mjcf/mjcf-graph.cpp
unittest/mjcf.cpp

This PR aims at fixing the bug described in https://github.com/stack-of-tasks/pinocchio/issues/2364

Fix Mjcf parsing of root joint

---

CHANGELOG.md
examples/simulation-closed-kinematic-chains.py
examples/simulation-contact-dynamics.py
examples/talos-simulation.py
unittest/mjcf.cpp

Fix the problems that were shown by https://github.com/stack-of-tasks/pinocchio/issues/2357.
Also remove a compilation warning coming from mjcf unittest.

Fix a few examples scripts

---

doc/d-practical-exercises/3-invkine.md

This is a follow-up from #2366

doc - Add explanations for null space projection.

---

CHANGELOG.md
bindings/python/pinocchio/visualize/rviz_visualizer.py

Fix abstract class error

---

CHANGELOG.md
examples/CMakeLists.txt
examples/inverse-kinematics-3d.cpp
examples/inverse-kinematics-3d.py

Add inverse-kinematics for translation error only

---

CHANGELOG.md
examples/cassie-simulation.py
examples/talos-simulation.py

- Fix talos-simulation.py
- Fix cassie-simulation.py

Fix some examples

---

CMakeLists.txt
pixi.toml

Hello,
This piece of code has been moved to the **jrl-cmakemodules** (https://github.com/jrl-umi3218/jrl-cmakemodules/pull/717)
Cheers

Remove small code duplication in CMakelists.txt for ROS2/Ament packaging

---

CHANGELOG.md
include/pinocchio/bindings/python/multibody/data.hpp
include/pinocchio/bindings/python/multibody/geometry-data.hpp
include/pinocchio/bindings/python/multibody/geometry-model.hpp
include/pinocchio/bindings/python/multibody/model.hpp

Hi again,
This fix https://github.com/stack-of-tasks/pinocchio/issues/2563, when https://github.com/loco-3d/crocoddyl/pull/1339 is also applied.

python: register Model

---

include/pinocchio/math/quaternion.hpp

Set back PINOCCHIO_DEFAULT_QUATERNION_NORM_TOLERANCE_VALUE definition

---

examples/casadi/CMakeLists.txt
examples/casadi/casadi-crba.cpp
include/pinocchio/spatial/inertia.hpp
unittest/casadi/spatial.cpp

Related to https://github.com/stack-of-tasks/pinocchio/issues/2635

Add CRBA CasADi example
