src/multibody/joint/joint-revolute-unaligned.hpp
The error in Joint Revolute Unaligned was the operator implying a spatial inertia and the ConstraintRevoluteUnaligned, needed by CRBA.
Using the script sent by antonio, now inertia_matrix_rnea and inertia_matrix_crba are equal ( some value to xx e-15 though)
=> [C++][Debug] Fixed operator * : Y*S in joint revolute unaligned

src/multibody/joint/joint-prismatic.hpp, src/multibody/joint/joint-revolute-unaligned.hpp, src/multibody/joint/joint-revolute.hpp
- This is necessary to build with older compiler versions.
- The keyword typename must only be used in template declarations
and definitions and only in contexts in which dependent names can
be used. This excludes explicit specialization declarations and
explicit instantiation declarations (until C++11).
=> [C++] Remove forbidden instances of typename keyword.

src/multibody/joint/joint-free-flyer.hpp, src/multibody/joint/joint-planar.hpp, src/multibody/joint/joint-prismatic.hpp, src/multibody/joint/joint-revolute-unaligned.hpp, src/multibody/joint/joint-revolute.hpp, src/multibody/joint/joint-spherical-ZYX.hpp, src/multibody/joint/joint-spherical.hpp, src/multibody/joint/joint-translation.hpp, src/multibody/model.hpp, src/spatial/motion.hpp
* Add inline specifier where needed.
* This is done to avoid multiple definition when using the pinocchio
library as a dependency.
* This should **partly** solve #47
=> [C++][Bug] Enforce One Definition Rule in template instantiations.

.travis.yml, travis_custom/custom_before_install
[travis] Build_type is now MinSizeRel to optimize the comsumption of … RAM during process in order to avoid crashes during travis builds. Display memory during build to track RAM information. Reduce number of dependencies
=> Try to avoid travis killed builds (i.e crashes due to building environment running out of ram)

src/multibody/model.hpp, src/multibody/parser/sample-models.hpp, src/multibody/parser/urdf.hpp, unittest/joints.cpp
* se3::Model::getBodyId was used to retrieve joint id in parsers.
* Implement new methods to retrieve joint ids.
* Fix body methods.
=> [C++][Bug] Avoid confusion between joint and body methods in se3::Model.

src/multibody/joint/joint-prismatic.hpp, src/multibody/joint/joint-revolute.hpp
@fvalenza You should always inline full template specializations.
I think this type of error can be easily checked if you build the benchmark in travis.
=> Enforce (again) One Definition Rule

.travis.yml
With the command travis_wait we give 20 minutes instead of 10 minutes before killing the build.
With this, issue #48  should be now fixed ( we need to  do more testing but i had 5/5 build success).
(travis_wait can take in argument the time we allow to wait. If no time is stated, then it is  20 minutes)
=> [travis] Give travis more time for executing full build

benchmark/timings.cpp, src/multibody/parser/urdf.hpp, src/python/model.hpp, src/python/parsers.hpp, src/python/robot_wrapper.py, src/python/romeo_wrapper.py, unittest/value.cpp
- The type of joint used as a root joint can now be specified by the user in C++ and in Python
- Add the possibility to create a model from scratch in python. To do so, first create an empty model using BuildEmptyModel(), then add one by one your joints with addBody(..args..)
- Also fixing a missing functionality : you now have properly access to the joints of the model.
Exemple
```
import pinocchio as se3
from pinocchio.romeo_wrapper import RomeoWrapper
myModel = se3.Model.BuildEmptyModel()
myModel.addBody(0, se3.JointModelFreeFlyer(), se3.SE3.Random(), se3.Inertia.Random(),"j1","b1",True)
myModel.addBody(1, se3.JointModelRX(), se3.SE3.Random(), se3.Inertia.Random(),"j2","b2",True)
joint =  myModel.joints[2]
print joint.idx_q
print joint.nq
```
=> create model using python & (fix) exposure of joints

src/CMakeLists.txt, src/multibody/parser/sample-models.cpp, src/multibody/parser/sample-models.hpp
* One Definition Rule was still not enforced.
* Declare function in header sample-model.hpp, implement them in
sample-models.cpp
* Add sample-models symbols to libpinocchio.
=> [C++][Bug] Move sample-models function implementations out of header.

src/multibody/parser/urdf.hpp
If a URDF link has no inertia tag, the spatial inertia is currently set to se3::spatial::Inertia::Identity(); the link mass is thus set to 1 kg and the inertia to the identity 3x3 matrix.
This PR fixes this issue by setting the spatial inertia to se3::spatial::Zero() instead.
=> Fix URDF inertia parser

src/python/model.hpp
This is a proposal to further emulate a python list using std::vector.
I don't know whether this is the best way to do it, but it works.
=> [Python] Add StdVec::index binding to emulate python list behavior.

src/multibody/parser/sample-models.cpp
* Velocity and torque limits are choosen randomly from the [0;1]
interval for 1D joints.
* Position limits are choosen randomly from the [-1;1] interval for
1D joints.
* Torque limits set to zero(6) for freeflyer joint.
* Velocity limits are choosen randomly from the [0, 1e3]^6
interval for freeflyer joint.
* Position limits are choosen randomly from the [-1e3, 1e3]^7
interval for freeflyer joint.
Freeflyer case could be better handled, maybe using std::numeric_limits. What do you think?
=> Build sample humanoid model with joint limits.

CMakeLists.txt, src/multibody/model.hpp, src/multibody/parser/urdf.hpp, src/python/inertia.hpp, src/python/model.hpp, src/spatial/inertia.hpp, src/spatial/symmetric3.hpp, unittest/com.cpp
This PR provides different improvements:
1. Initialize with NaN all the kinematics and dynamics quantities in Debug mode (useful for python users) (solves #62) 
2. Expose some methods of spatial quantities for easier modifications
3. Correct a bug for the returning index
=> Set default initialization of variables + expose spatial quantities methods + correct bug

src/algorithm/jacobian.hpp, src/multibody/parser/urdf.hpp
The functions should be inlined, otherwise it breaks when the headers
are used several times in the same application. An application with multiple robots will be in such case.
=> Functions defined in headers urdf.hpp and jacobian.hpp are set to inline.

src/multibody/parser/from-collada-to-fcl.hpp, src/multibody/parser/urdf-with-geometry.hxx
Runtime error killed python when meshes were not found.
=> Throw exception when parsing meshes instead of runtime error

src/math/sincos.hpp
This feature is needed for OS having no sincos function.
=> Set default SINCOS for architecture with no sincos function

benchmark/timings-geometry.cpp, benchmark/timings.cpp, src/algorithm/center-of-mass.hpp, src/algorithm/center-of-mass.hxx, src/python/algorithms.hpp, src/python/data.hpp, src/python/geometry-data.hpp, src/python/robot_wrapper.py, src/simulation/compute-all-terms.hpp, unittest/com.cpp
There is now only one name for center of mass computations which is centerOfMass with different signatures.
The Python is now changed to follow the same standard of a unique method name for forwardKinematics with several signatures.
=> Rework center of mass algo + Python API

src/algorithm/dynamics.hpp, src/multibody/model.hpp, src/multibody/model.hxx, src/python/data.hpp, unittest/dynamics.cpp
You can not access data.lambda in Python, because the interpreter throws a `SyntaxError: invalid syntax`
=> [Python] lambda is a reserved keyword

.travis.yml, CMakeLists.txt, src/algorithm/collisions.hpp, src/multibody/geometry.hpp, src/multibody/geometry.hxx, src/multibody/parser/urdf-with-geometry.hpp, src/multibody/parser/urdf-with-geometry.hxx, src/python/geometry-data.hpp, src/python/geometry-model.hpp, src/python/geometry-object.hpp, src/python/python.cpp, unittest/geom.cpp
ed in GeometryModel. Now it is two lists of GeometryObject (one for collisions, one for visuals) aggregating information instead of multiple vectors. Now handle multiple collisions/visuals for one link when parsing urdf file and keep track of the mesh absolute path. Changed binding accordingly.
=> [C++][Python][Major] Replaced the way collisions and visuals are stored

src/multibody/joint/joint-free-flyer.hpp, src/multibody/joint/joint-spherical.hpp
Fix bug in the differentiate implementation of joint free flyer and spherical when the two configurations are equal.
=> Handle the zero velocity case for spherical joint types

src/multibody/model.hpp
This allow to use `new se3::Model m` and `new se3::Data(m)`. This problem is specific to eigen.
=> overload the new operator for the model and data classes

src/multibody/joint/joint-accessor.hpp, unittest/joint-accessor.cpp
JointAccessor now inherits both from JointBase and JointVariant. It is thus now a variant respecting the Base interface, hiding the calls to visitor.
Added some copy operator in order to allow to build a vector of JointAccessor.
Related to #131
=> Make JointAccessor a variant on its own and a Derived Joint

src/multibody/parser/from-collada-to-fcl.hpp
Triangulated meshes contain faces with 1, 2 or 3 vertex. Faces with 1 and 2 vertex are not supported by FCL.
Refers to humanoid-path-planner/hpp-model-urdf#6
=> Add exception when loading meshes with lines.

python/bindings_geometry_object.py, python/tests.py, src/multibody/model.hpp, src/multibody/model.hxx, src/multibody/parser/lua.cpp, src/multibody/parser/sample-models.cpp, src/multibody/parser/urdf-with-geometry.hxx, src/multibody/parser/urdf.hxx, src/python/model.hpp, src/python/robot_wrapper.py, unittest/geom.cpp, unittest/joint-accessor.cpp, unittest/joint-configurations.cpp, unittest/joints.cpp
- Make the separation between bodies and joints and do modifications according to.
- Fixed RobotWrapper display : now correctly get the visuals from the geometrymodel/data, update it and display. The meshes are loaded in the viewer one by one thanks to the mesh_path stored by the GeometryObject itself. Removed some useless informations such as _has_visual_ and _fixedBodies_ that were informations related to visual stuff.
Related to #126 , #161
=> rework model (joints/bodies) + fix RobotWrapper link to viewer

src/multibody/constraint.hpp, src/multibody/joint/joint-free-flyer.hpp, src/multibody/joint/joint-planar.hpp, src/multibody/joint/joint-prismatic-unaligned.hpp, src/multibody/joint/joint-prismatic.hpp, src/multibody/joint/joint-revolute-unaligned.hpp, src/multibody/joint/joint-revolute.hpp, src/multibody/joint/joint-spherical-ZYX.hpp, src/multibody/joint/joint-spherical.hpp, src/multibody/joint/joint-translation.hpp, src/multibody/parser/urdf.hxx, src/python/force.hpp, src/python/inertia.hpp, src/python/motion.hpp, src/python/se3.hpp, src/spatial/force.hpp, src/spatial/fwd.hpp, src/spatial/inertia.hpp, src/spatial/motion.hpp, src/spatial/se3.hpp
* Rename Scalar_t to Scalar.
* This allows applying Eigen-compatible template operations to
se3::spatial objects.
=> [C++] Rename spatial scalar type to follow Eigen convention.

src/spatial/se3.hpp
=> [Spatial][Minor] Make SE3 constructor from rotation explicit 

src/algorithm/center-of-mass.hpp
I lost quite some time looking for a bug caused by this. It may help somebody later.
By the way, I find it a bit confusing that `centerOfMass` and `jacobianCenterOfMass` fills the same data but in different frames.
=> Fix doc of jacobinCenterOfMass

src/multibody/geometry.hpp
=> CollisionPair does not invert indexes. Add CollisionPair::operator==

src/algorithm/geometry.hpp, src/algorithm/geometry.hxx
For a rather cheap update, we can have `computeDistances` returning the index corresponding to the shortest distance.
I hesitated between this version and a templatized version like `computeDistances<ReturnShortest>(...)`. As the shortest distance is rather cheap to compute, I think it does not matter do always do it.
=> se3::computeDistances return the index of the shortest distance.

src/multibody/fwd.hpp, src/spatial/force.hpp, src/spatial/fwd.hpp, src/spatial/inertia.hpp, src/spatial/motion.hpp, src/spatial/se3.hpp, src/spatial/symmetric3.hpp
This decreases headers inter-dependency. It helps reducing compilation time of libraries downstream.
=> [C++] Add missing forward declaration.

bindings/python/model.hpp, bindings/python/se3.hpp, src/algorithm/frames.hpp, src/multibody/frame.hpp, src/multibody/joint/joint-free-flyer.hpp, src/multibody/joint/joint-planar.hpp, src/multibody/joint/joint-spherical.hpp, src/multibody/model.hpp, src/spatial/se3.hpp, unittest/finite-differences.cpp, unittest/tspatial.cpp
Some methods have been set to deprecated inside the model (getFrameParent, getFrameName, etc) has they are directly accessible from the `frames` vector. A new clean of model will be proposed in the very next future.
=> Update the Frame the part + expose new methods

benchmark/timings-geometry.cpp, bindings/python/algorithm/expose-geometry.cpp, bindings/python/frame.hpp, bindings/python/geometry-data.hpp, bindings/python/geometry-model.hpp, bindings/python/geometry-object.hpp, bindings/python/model.hpp, python/bindings_frame.py, python/bindings_geometry_object.py, src/multibody/model.hpp, src/multibody/model.hxx
The python binding will not compile on Travis because hpp-fcl does not provide yet an operator == for DistanceResults  (needed by vector_indexing_suite). I will make a PR in hpp-fcl for that)
=> [C++] Fixed compilation errors due to changes of API

bindings/python/geometry-data.hpp
Previous PR has been merged before i pushed this commit.
As we don't know yet if hpp-fcl will integrate the operator== for DistanceResult, i've put it where it is needed in Pinocchio
=> [Python][hpp-fcl] Provide temporary operator== for DistanceResult.

src/math/quaternion.hpp, src/multibody/joint/joint-free-flyer.hpp, src/multibody/joint/joint-spherical.hpp
- fix uniform sampling of quaternions
- update doc
- update assert threshold
I think it would be nice to add a unittest doing plenty of integration for a spherical joint and checking that the norm of the quaternion is always close to 1.
=> Update quaternions related operations

CMakeLists.txt, bindings/python/joint.hpp, src/multibody/joint/fwd.hpp, src/multibody/joint/joint-composite.hpp, src/multibody/joint/joint-variant.hpp, src/multibody/joint/joint.hpp, src/multibody/model.hpp
Related to #336.
The circular inclusion is removed. One just relies on `pinocchio/multi body/joint/joint.hpp`to get access to all the joints.
=> Replacement Joint{Model,Data} with Joint{Model,Data}Variant in JointModelComposite

CMakeLists.txt, bindings/python/data.hpp, bindings/python/frame.hpp, bindings/python/geometry-data.hpp, bindings/python/geometry-model.hpp, bindings/python/model.hpp, src/container/aligned-vector.hpp, src/multibody/fcl.hpp, src/multibody/frame.hpp, src/multibody/geometry.hpp, src/multibody/geometry.hxx, src/multibody/joint/joint.hpp, src/multibody/model.hpp, src/multibody/model.hxx
Introduce a new type container::aligned_vector which an easy specialisation of std::vector of aligned Types.
=> Fix bug in alignment of std::vector

src/tools/file-explorer.hpp
Last path was not retrieved. I locally added a separator ":" at the end of ROS_PACKAGE_PATH environment variable to fix the bug.
=> Fix bug in parsing of ROS_PACKAGE_PATH variable

src/algorithm/geometry.hxx
There was a confusion between radius and radius squared.
=> Fix bug in computeBodyRadius

CMakeLists.txt, bindings/python/algorithm/expose-joints.cpp, src/algorithm/joint-configuration.hpp, src/math/quaternion.hpp, src/multibody/joint/fwd.hpp, src/multibody/joint/joint-base.hpp, src/multibody/joint/joint-free-flyer.hpp, src/multibody/joint/joint-planar.hpp, src/multibody/joint/joint-prismatic-unaligned.hpp, src/multibody/joint/joint-prismatic.hpp, src/multibody/joint/joint-revolute-unaligned.hpp, src/multibody/joint/joint-revolute-unbounded.hpp, src/multibody/joint/joint-revolute.hpp, src/multibody/joint/joint-spherical-ZYX.hpp, src/multibody/joint/joint-spherical.hpp, src/multibody/joint/joint-translation.hpp, src/multibody/liegroup/cartesian-product.hpp, src/multibody/liegroup/liegroup.hpp, src/multibody/liegroup/operation-base.hpp, src/multibody/liegroup/operation-base.hxx, src/multibody/liegroup/special-euclidean.hpp, src/multibody/liegroup/special-orthogonal.hpp, src/multibody/liegroup/vector-space.hpp, src/spatial/explog.hpp, unittest/CMakeLists.txt, unittest/joint-composite.cpp, unittest/liegroups.cpp
The spaces taken into account are SO1, SO3, SE1, SE3, vector spaces and the Cartesian product of two of them.
The association `JointModel` <-> `LieGroupOperationBase` derived classes is made by the class `LieGroup` in file `src/multubody/liegroup/liegroup.hpp`.
Comments are welcome. Please focus first on important matters, such as names and architectures.
I emphasize the following points:
- name `SpecialOrthogonal1` and  `SpecialEuclidean1` are both very ugly and should be 2 instead of 1.
- `SpecialEuclidean1::forwardKinematics` seems weird to me (naming or architecture problem?).
Solves #344
=> [C++] Move space operation to new class LieGroup and inherited classes.

src/parsers/urdf/model.cpp
In both cases, the frame tree starts with frame "root_joint"
=> [Minor][C++] Homogenize behaviour of URDF regarding root joint.

src/spatial/fcl-pinocchio-conversions.hpp, unittest/geom.cpp
hpp-fcl will use only Eigen types in future version.
The FCL_HAVE_EIGEN makes it compatible with older version of hpp-fcl. See comment in src/spatial/fcl-pinocchio-conversions.hpp for more details.
Note that at the moment, the copy is temporarily needed but can be removed when hpp-fcl is upgraded.
=> Update to last changes in hpp-fcl

src/algorithm/joint-configuration.hpp, src/multibody/liegroup/cartesian-product.hpp, src/multibody/liegroup/operation-base.hpp, src/multibody/liegroup/operation-base.hxx, src/multibody/liegroup/special-euclidean.hpp, src/multibody/liegroup/special-orthogonal.hpp, src/multibody/liegroup/vector-space.hpp, unittest/liegroups.cpp
In the previous implementation, vector space of dynamic size were ill defined and random sampling was not correct.
With this pull request, random sampling is possible for vector spaces of dynamic size.
=> Lie group operation struct are aware of the dimension of the element they manipulate

src/spatial/explog.hpp
Previous implementation did not accept a vector of dynamic size of size 3.
This commit fixes the issue.
=> In exp3, modify assertion

bindings/python/multibody/model.hpp, bindings/python/parsers/parsers.hpp
Fix access to boost::variant::extract in model.hpp and parsers.hpp.
=> [c++11] Making pinocchio compiles with c++11

src/multibody/joint/joint-base.hpp
I am pretty sure this is a bug. There was a \ missing, thereby breaking the definition of the macro.
This should only happen when compiling with GCC 4.4.2 . Haven't tested it, but the problem seems obvious.
Speaking about it, it seems very weird to me that the compiler version is apparently checked for equality, instead of using >= or <= . Is there a reason for it?
=> Fix TYPEDEF for GNUC 442

unittest/CMakeLists.txt
It also corrects a bad behaviour of ctest command under OSX
=> Handle recent version of boost >= 1.67.0

src/multibody/liegroup/operation-base.hxx
This bug is appearing with Eigen3 >= 3.3.4.
The scalar product return type does not have an Options which is required by exp3.
=> [LieGroup] Fix bug related to the Scalar product return type

src/multibody/liegroup/special-euclidean.hpp, src/multibody/liegroup/special-orthogonal.hpp, unittest/liegroups.cpp
Otherwise, distance between equal configurations may not be equal to 0.
=> In SE(n) and SO(n), difference is exactly zero if operands are equal.

benchmark/timings.cpp, bindings/python/CMakeLists.txt, bindings/python/algorithm/expose-frames.cpp, bindings/python/algorithm/expose-jacobian.cpp, bindings/python/scripts/__init__.py, bindings/python/scripts/deprecated.py, bindings/python/scripts/derivative/dcrba.py, bindings/python/scripts/robot_wrapper.py, src/algorithm/center-of-mass.hpp, src/algorithm/compute-all-terms.hpp, src/algorithm/frames.hpp, src/algorithm/frames.hxx, src/algorithm/jacobian.hpp, src/algorithm/jacobian.hxx, src/algorithm/kinematics-derivatives.hpp, src/multibody/data.hpp, unittest/aba-derivatives.cpp, unittest/aba.cpp, unittest/compute-all-terms.cpp, unittest/crba.cpp, unittest/dynamics.cpp, unittest/finite-differences.cpp, unittest/frames.cpp, unittest/jacobian.cpp, unittest/joints.cpp, unittest/kinematics-derivatives.cpp, unittest/rnea-derivatives.cpp, unittest/rnea.cpp
Some functions working on Jacobian have been renamed:
- getJacobian is now getJointJacobian
- computeJacobians is now computeJointJacobians
- getJacobianTimeVariation is now getJointJacobianTimeVariation
- computeJacobiansTimeVariation is now getJointJacobianTimeVariation
It follows some discussions occurred in #432
=> Update function name when considering joint Jacobian

.gitlab-ci.yml
Hi,
This PR updates the gitlab CI configuration file to use a dedicated build target for generating the documentation and the coverage reports of this project.
It is also ready to add build targets in DEBUG mode if needed.
=> [CI][Gitlab] Use a dedicated target for generating doc and coverage

src/spatial/explog.hpp
This new expression comes from the fact that [w]x*[w]x = w*w.T -
\|x\|^2. For more information see "Differential of the Exponential Map":
http://ethaneade.org/exp_diff.pdf
=> [core] Efficient implementation of exp6

src/algorithm/dynamics.hpp, unittest/dynamics.cpp
This PR is continuation of PR #500 
In test_fd_with_damping, the constraints (J) are repeated twice. So, while the dimension of the constraints is 12, the rank is 6.
Notes:
When trying to find the undamped solution to the test given in test_fd_with_damping, I discovered that cholesky decomposition was still able to find a solution. This is not what I observed when using a reduced HRP2 model and constraints on the two feet (which were rank deficient).
=> Documentation and unittest for forward dynamics with damped cholesky inverse

doc/outline.txt
After discussing with Nicolas, I changed the outline of the doc.
I think the doc should be modeled on Eigen's "long tutorial": a series of pages, each covering a topic from the user point of view, with worked examples in the form of short snippets intertwined with the code.
Then the proper tutorials will contain larger in-depth examples.
The technical part, containing implementation details, should be separate.
So, the main user doc in a part I called  "Features". As "List of features" should closely reflect the content of "Features", I removed all content from the former part and put in into the latter.
Also, I moved the math to later in the doc, as discussed
=> [Doc] Revision of outline after discussion with Nicolas.

bindings/python/algorithm/expose-frames.cpp, bindings/python/scripts/deprecated.py, bindings/python/scripts/deprecation.py, bindings/python/scripts/robot_wrapper.py, src/algorithm/frames.hpp, src/algorithm/frames.hxx, src/algorithm/jacobian.hpp, unittest/frames.cpp
framesForwardKinematics(model, data, frame_id) computes oMf[frame_id], stores it and returns it. Assumes forwardKinematics has already been run. Thought it might be useful if the model contains many frames but we are only interested in one or two of them.
getFrameVelocity(model, data, frame_id, v_frame) computes the velocity of frame frame_id and puts it in v_frame. Assumes first-order forwardKinematics has already been run.
getFrameAcceleration(model, data, frame_id, a_frame) computes the acceleration of frame frame_id and puts it in a_frame. Assumes second-order forwardKinematics has already been run.
=> [frames] Helper functions for frames

.gitlab-ci.yml, bindings/python/parsers/python/model.cpp
Hi,
This PR updates the gitlab CI configuration by:
- compiling both robotpkg-pinocchio & robotpkg-py-pinocchio on the current commit
- using docker images with `CMAKE_ARGS += -DBUILD_UNIT_TESTS=ON`
- ignore failing tests on python3 for now
and fixes the tests on python2 / ubuntu xenial, which uses boost python v1.58, which has a bug in `exec_file`.
=> Fix Boost 1.58 usage, and update gitlab-ci

src/spatial/inertia.hpp, src/spatial/skew.hpp, src/spatial/symmetric3.hpp
The \cross command employed in many doxygen comment formulas is not recognized by latex, causing an error message to be shown in place of the whole formula when the html is displayed on a browser. This is what happens on my system at least. The problem is \cross is not part of amsmath nor amssymb, \times should be used instead.
I replaced all occurrences of \cross with \times.
I didn't know which branch would be more appropriate, I put it in topic/doc-v2 for now.
The other option is to get doxygen to accept \cross. This needs to be done in the cmake submodule, I think. For that, ALIASES does not seem to work, I think one would need to create a custom latex package that does nothing more than defining \cross (maybe to be identical to \times) and then add this package to the Doxyfile …
=> [doxygen] [minor] replaced \cross with \times in doxygen formulas

.gitlab-ci.yml
Hi,
with `--exclude bindings/python`, the coverage went from:
```
TOTAL                                      10764    9832    91%
```
to
```
TOTAL                                      10331    9503    91%
```
=>  [Coverage] Temporarly exclude bindings/python directory from coverage reports, fix #534

.gitlab-ci.yml
Hi,
This PR follows #538 which has already been merged.
The coverage now goes from 92.0 to 93.3:
http://projects.laas.fr/gepetto/doc/gsaurel/pinocchio/devel/coverage/
=> [Coverage] fix regex to find bindings/python in some subdirs, ref #534

bindings/python/multibody/model.hpp, bindings/python/parsers/sample-models.hpp, bindings/python/scripts/deprecated.py, src/parsers/sample-models.hpp
Correct the bindings for the newly-introduced models.
- expose `buildSampleModelHumanoidRandom` in python
- deprecate `buildSampleModelHumanoidSimple` in python
- deprecate static method `Model.BuildHumanoidSimple` in python
- add overloads for `buildSampleModelHumanoid` and `buildSampleModelHumanoidRandom` in python (for `usingFF`)
Two observations:
- `buildSampleModelHumanoidSimple` was introduced by @nmansard in his last commits. Since it calls a function which is deprecated in C++, I thought it should be deprecated in python too. Until now, the way to create a simple humanoid in python was to call static method `Model.BuildHumanoidSimple`, which was calling the deprecated C++ function. It needs to be deprecated too if the warning has to appear in existing python code. Also, I think …
=> [bindings] [sample models] Manage deprecation and overloads in python

src/math/sincos.hpp, unittest/CMakeLists.txt, unittest/sincos.cpp
It overloads the previous macro for various types {float,double,long double}.
It fixes issue #559
=> Fix sincos for floats

src/parsers/sample-models.cpp, unittest/python/bindings_geometry_object.py
For some reason, the corrections I had made to  unittest/python/bindings_geometry_object.py seem to have been eaten up by last merge, so I restored them.
While correcting, I discovered a bug which was introduced with Pinocchio 2.0 in the sample geometry models, so I fixed it. Basically the parent joint of the geometry objects was not set correctly.
This is due to the fact that, before, `geommodel.addGeometryObject(object, model, bool)` was employed and this method was taking care of setting the parent. But in Pinocchio 2.0, this method was deprecated and replaced by `geommodel.addGeometryObject(object)`, leaving the parent joint unset.
=> [bug] Fix sample geometry model and python geometry unit test

bindings/python/CMakeLists.txt, bindings/python/algorithm/expose-com.cpp, bindings/python/algorithm/expose-dynamics.cpp, bindings/python/algorithm/expose-rnea-derivatives.cpp, bindings/python/algorithm/expose-rnea.cpp, bindings/python/scripts/deprecated.py, bindings/python/scripts/robot_wrapper.py, bindings/python/scripts/shortcuts.py, unittest/python/bindings_dynamics.py, unittest/python/tests.py
- turned impactDynamics to impulseDynamics in python, deprecated impactDynamics
- exposed nonLinearEffects, but left nle available as a shorthand
- exposed computeGeneralizedGravity
- exposed computeCoriolisMatrix
- exposed computeGeneralizedGravityDerivatives
- exposed all available overloads of impulseDynamics
- exposed all available overloads of forwardDynamics
- turned RobotWrapper.bias to RobotWrapper.nle, deprecated RobotWrapper.bias
- used newly exposed computeGeneralizedGravity instead of rnea in RobotWrapper.gravity
=> [bindings] Implement bindings, solve name inconsistencies, fix #529

src/multibody/geometry.hpp
Method `addGeometryObject(object,model,bool);` is now deprecated, but it contained a small bug, so I fixed it (it was causing a warning)
=> [geometry] fix addGeometryObject

doc/Doxyfile.extra.in, src/multibody/data.hxx, src/multibody/joint/joint-collection.hpp, src/multibody/joint/joint-revolute.hpp, src/multibody/liegroup/liegroup-base.hpp, src/parsers/sample-models.cpp, src/parsers/sample-models.hpp, src/parsers/sample-models.hxx
I am finalizing the tests in HPP using Pinocchio v2.
I played a bit with JointCollection. I have one minor question. Is there a reason to use:
```cpp
template<typename Scalar, int Options=0,
template<typename,int> class JointCollectionTpl = JointCollectionDefaultTpl>
struct Model
```
rather than this:
```cpp
template<typename Scalar, int Options=0,
class JointCollection = JointCollectionDefaultTpl<Scalar, Options> >
struct Model
```
?
With the current option, it is not possible to do:
```cpp
template <template<typename,int> class JointCollectionTpl>
void some_function_I_want_to_call (...)
some_function_I_want_to_call <Model::JointCollection> (...)
```
=> Set of minor fixes

bindings/python/multibody/joint/joints-models.hpp, bindings/python/multibody/joint/joints-variant.hpp, bindings/python/scripts/deprecated.py, bindings/python/scripts/explog.py, bindings/python/spatial/explog.hpp, bindings/python/spatial/expose-explog.cpp, src/multibody/joint/joint-composite.hpp, src/multibody/joint/joint-prismatic-unaligned.hpp, src/multibody/joint/joint-revolute-unaligned.hpp, unittest/python/bindings.py, unittest/python/bindings_joint_composite.py, unittest/python/explog.py, unittest/python/model.py, unittest/python/rpy.py, unittest/python/tests.py, unittest/python/utils.py
- exposed constructors and axis for JointModelPrismaticUnaligned and JointModelRevoluteUnaligned
- exposed some constructors and addJoint for JointModelComposite
- fixed bugs in python's explog
- related minor stuff
While working on the unit test for JointModelComposite, I found the unit tests using explog were not working any more, so I fixed them.
As a rule of thumb, If we have unit tests, better use them
=> Joint bindings + fix explog

bindings/python/spatial/explog.hpp, bindings/python/spatial/expose-explog.cpp
It seems that the desctructor invoked by eigenpy does not fit with the constructor invoked in Pinocchio.
This PR is related to #597
=> bindings/python: fix bug related to eigenpy

bindings/python/scripts/deprecated.py, bindings/python/scripts/explog.py, src/spatial/explog.hpp, unittest/explog.cpp, unittest/python/explog.py
The bindings for explog were not working.
I obtained segmentation faults and/or wrong results when using fixed-size types as template parameters, so I had to switch to dynamic size (tested on my computer and on @jmirabel's laptop).
Apparently, this only happens when Pinocchio is compiled in *Release* mode. It does not happen in Debug mode, and it does not happen when neither Debug nor Release is specified.
It seems the problem is related to eigenpy. We only tested for eigenpy in Release mode.
This pull request patches the problem for explog in Pinocchio, but the problem in eigenpy should be investigated.
=> [bindings] fix explog

bindings/python/multibody/joint/joint-derived.hpp, bindings/python/multibody/joint/joint.hpp, bindings/python/multibody/joint/joints-models.hpp, bindings/python/multibody/joint/joints-variant.hpp, bindings/python/scripts/robot_wrapper.py, bindings/python/scripts/romeo_wrapper.py, examples/python/load-urdf.py, src/multibody/joint/joint-composite.hpp, unittest/joint-composite.cpp, unittest/python/bindings_joint_composite.py
Mostly python fixes
- Fixed a few things in `RobotWrapper` and `RomeoWrapper`
- Finished exposing `JointModelComposite` constructors and data
- Additionally, I slightly modified `addJoint` in `JointModelComposite`.
It now returns a reference to the same joint being modified, so that the expressions can be easily chained, as in
`joint_composite.addJoint(joint1).addJoint(joint2).addJoint(joint3);`
=> [python] [JointModelComposite] Various fixes

doc/_porting.md
Update the porting notes.
Mostly cosmetic changes, but I added a subsection explaining Pinocchio is now header-only, plus additional clarifications on the deprecated macros. @jcarpent may you check it is correct?
I'm directly updating the devel branch, rather than topic/doc-v2 (see PR #605). This is to make the changes immediately available to anybody working with devel.
=> [doc] Update porting notes

doc/Doxyfile.extra.in, doc/customdoxygen.css, doc/treeview.dox, src/algorithm/centroidal-derivatives.hpp, src/multibody/fwd.hpp, src/multibody/joint/fwd.hpp, src/spatial/explog.hpp, src/spatial/fwd.hpp, src/spatial/skew.hpp
Hi,
I've started working on cleaning the Doxygen-generated documentation, turns out it will require more work than I expected.
As for now, I have hidden a few irrelevant things and added the typedefs to their groups, and fixed some latex-related errors. Also, I've added a custom CSS style sheet. I used it to break ling template names inside tables which were making the whole thing unreadable. It is a bit less messy now.
Notice the documentation for /d-practical-exercises/src/ was generated too. I explicitly ignored it, but an alternative would be to move it to a top-level directory, called, e.g., exercises or labs.
=> [doc] Work on Doxygen

bindings/python/algorithm/expose-aba-derivatives.cpp, bindings/python/algorithm/expose-joints.cpp
I worked a bit with the derivative algos that I never tried before. Very nice work. It like them a lot!
I added a direct and naive binding to the derivative of the joint integration. I believe that it follows the naive joint algorithm implemented in src/algo. Should we had some comment in the documentation (both of the python and the c++ function) to specify that this algorithm is best used at the joint level, using the sparsity of the kinematic tree?
I added a copy of the current ABA derivative to account for external forces, following the pattern of the rnea algorithm. 
NB: 
Meanwhile, I noticed that some StdVector bindings are named StdVec while others are named StdVect. I guess we should unified. I would be interest to now the best way for creating a filled StdVec. I was not able to …
=> Added bindings to derivative algorithms

bindings/python/multibody/fcl/collision-geometry.hpp, bindings/python/multibody/fcl/collision-result.hpp
There are some work being done in hpp-fcl currently. It should be stabilized by the end of the week. It should not impact Pinocchio except for the following changes.
The following three functions are now marked as deprecated.
```
.def("isOccupied",&CollisionGeometry::isOccupied)
.def("isFree",&CollisionGeometry::isFree)
.def("isUncertain",&CollisionGeometry::isUncertain)
```
Should I remove them from the bindings ?
The reason why only `isOccupied` is removed for now is historical. I will change this once we agree on the strategy.
=> [Python] Update to changes in hpp-fcl.

README.md
I find pointing to the folder rather than the README.md is clearer. Note: you still see the README.md at the bottom of the page with the new link.
I was a bit confused when I clicked and only saw the README and thought "but where are the examples I wanted to look at?".
=> Improve link for Python examples

models/simple_humanoid.srdf, src/parsers/srdf.hxx, unittest/srdf.cpp
Currently when loading neutralConfiguration from srdf, root_joint values are not loaded.
This PR should change that.
=> Load neutralconfiguration from srdf for joint.nq()>1

CMakeLists.txt
This PR adds support for both the existing/robotpkg hpp-fcl as well as the [catkinized hpp-fcl](https://github.com/ipab-slmc/hpp-fcl_catkin). The default behaviour does not change.
=> Support for catkinized hpp-fcl

bindings/python/multibody/fcl/collision-geometry.hpp, bindings/python/multibody/fcl/collision-result.hpp, bindings/python/multibody/fcl/contact.hpp, bindings/python/multibody/fcl/distance-result.hpp, bindings/python/multibody/fcl/expose-fcl.cpp, bindings/python/multibody/fcl/mesh-loader.hpp, bindings/python/parsers/parsers.hpp, bindings/python/scripts/robot_wrapper.py, src/multibody/fcl.hpp, src/parsers/urdf.hpp, src/parsers/urdf/geometry.hxx, src/spatial/fcl-pinocchio-conversions.hpp
Needs https://github.com/humanoid-path-planner/hpp-fcl/pull/50
=> [Parser] Provide API to avoid creating twice the same FCL geometry. 

bindings/python/algorithm/expose-kinematics-derivatives.cpp, src/algorithm/center-of-mass-derivatives.hpp, src/algorithm/center-of-mass-derivatives.hxx, unittest/CMakeLists.txt, unittest/center-of-mass-derivatives.cpp, unittest/python/bindings_com_velocity_derivatives.py, unittest/python/tests.py
I put the algo in a new center-of-mass-derivative.hpp/xx file, with new unittest file, following the policy used for other *-derivatives.hpp/xx files.
I put the binding in expose-kinematic-derivatives because creating a new file at this point seemed overkilled, but I can modify that choice if need be.
The algorithm is computed in the local frame, which makes it compact and elegant. I validated it for the simple humanoid in the unittest, but also for talos arm and legs in python.
=> Algorithm to compute the derivatives of the COM velocity

bindings/python/algorithm/expose-dynamics.cpp, src/algorithm/dynamics.hpp, unittest/dynamics.cpp
Currently the matrix decompositions done in forwardDynamics are wasted when computing the inverse of the MJtJ matrix. This PR adds a function that returns the analytical inverse of MJtJ (via schur complement) using the computations already done in forwardDynamics. This is also true for impulsedynamics.
I add the unittest and python bindings for this function as well.
=> get the inverse of MJtJ matrix using the matrix decompositions performed in forwardDynamics or impulsedynamics

src/multibody/joint/joint-revolute-unbounded.hpp, src/multibody/joint/joint-revolute.hpp, src/multibody/liegroup/vector-space.hpp, src/parsers/lua.cpp, src/parsers/lua/lua_tables.cpp, unittest/cholesky.cpp, unittest/liegroups.cpp, unittest/rnea.cpp, unittest/variant.cpp
Remove redundant semicolon in source files.
=> Remove redundant semicolons

src/algorithm/center-of-mass-derivatives.hxx, unittest/python/bindings_com_velocity_derivatives.py
With assertions enabled, center-of-mass-derivatives gave a compilation error due to a misnamed variable (which was not seen in Release mode because the assertion is simply skipped).
I fixed it. I grabbed the occasion to change `import pinocchio as pio` -> `import pinocchio as pin` in the corresponding unit test.
=> Fix center of mass derivatives debug compilation error

bindings/python/spatial/se3.hpp, unittest/python/bindings_com.py, unittest/python/bindings_dynamics.py, unittest/python/test_case.py
Fixes #677. Related to #673. The error on `explog.py` was actually due to the binding of `SE3.isIdentity()` which was crashing. I do not understand why there was this problem and why only in Debug mode, but I fixed it.
The error on `bindings_com.py` and `bindings_dynamics.py` was just a trivial error in the unit test itself (wrong vector size). I corrected it. Which makes me think, wouldn't it be better to enable assertions the Python library? If yes, is there any way to treat a failing assertion as an exception instead of having Python crash completely when one fails?
=> Fix python unit tests, fix #677

bindings/python/scripts/deprecated.py
Earlier, model.neutralConfiguration is set when getNeutralConfiguration was called from python.
With #666, I introduced a bug where calling getNeutralConfiguration does not set model.neutralConfiguration.
This PR is to fix that bug.
=> [bindings][loadReferenceConfig] fix bug when deprecated function is called

src/algorithm/joint-configuration.hpp, src/algorithm/joint-configuration.hxx, src/multibody/liegroup/liegroup-algo.hxx, unittest/joint-configurations.cpp
Fix #658.
Now all joint-configuration algorithms have two versions: one with return value as argument, and one which allocates memory.
Notice that most algorithms will probably give wrong results if the output is the same object as one of the inputs. This is true in particular for `integrate`. I might implement `integrateInPlace` in the future.
Additionally, I re-implemented `distance` so that it does not employ the auxiliary vector provided by `squaredDistance`.
Also, I am providing the square of the distance with method `squaredDistanceSum`, because `squaredDistance` was already taken. By the way, I think `squaredDistance` is pretty useless now that it is not employed by `distance`, should it be eliminated, and its name recycled for what I called `squaredDistanceSum`?
=> Reimplement joint-configuration algorithms, fix #658

bindings/python/multibody/data.hpp, bindings/python/multibody/model.hpp, bindings/python/utils/pickle-map.hpp, bindings/python/utils/pickle-vector.hpp, bindings/python/utils/std-aligned-vector.hpp, bindings/python/utils/std-vector.hpp
With this I believe all elements of model and data classes are now picklable.
=> Add support for pickling std vector, std aligned vector and std map

bindings/python/multibody/joint/expose-joints.cpp, bindings/python/multibody/joint/joint-derived.hpp, bindings/python/multibody/joint/joints-datas.hpp, bindings/python/multibody/joint/joints-variant.hpp, src/multibody/joint/joint-base.hpp, src/multibody/joint/joint-basic-visitors.hxx, src/multibody/joint/joint-composite.hpp, src/multibody/joint/joint-free-flyer.hpp, src/multibody/joint/joint-generic.hpp, src/multibody/joint/joint-planar.hpp, src/multibody/joint/joint-prismatic-unaligned.hpp, src/multibody/joint/joint-prismatic.hpp, src/multibody/joint/joint-revolute-unaligned.hpp, src/multibody/joint/joint-revolute-unbounded.hpp, src/multibody/joint/joint-revolute.hpp, src/multibody/joint/joint-spherical-ZYX.hpp, src/multibody/joint/joint-spherical.hpp, src/multibody/joint/joint-translation.hpp
This PR primarily creates the python bindings for the joint data classes.
In order to achive that, there are the following changes inside the JointData structs:
1) adding a shortname/classname visitor and function
2) adding a default constructor for JointDataComposite
3) create an ostream operator for making the classes printable
The rest of the PR deals with the python bindings of the JointData variants.
I don't expose JointData::F, since I didn't really understand why it is there. I'll add it if #683 is resolved that way.
=> Create python objects for JointData classes

bindings/python/multibody/model.hpp, bindings/python/pinocchio/__init__.py, bindings/python/pinocchio/deprecated.py, bindings/python/pinocchio/deprecation.py
`neutralConfiguration` is now deprecated in Python too. To achieve this, I exposed it as `_neutralConfiguration` and then I created a `neutralConfiguration` property raising the warning.
=> Deprecate neutralConfiguration in Python

src/multibody/joint/joint-revolute.hpp
=> joints: fix return type of translation() or rotation() methods

bindings/python/pinocchio/robot_wrapper.py, examples/python/gepetto-viewer.py, examples/python/meshcat-viewer.py
RobotWrapper now supports transparently the use of MeshCat as a 3D viewer, alongside of gepetto-gui.
Added example script to show how to use the MeshCat viewer.
Fix the gepetto-gui example script.
Linked to https://github.com/stack-of-tasks/pinocchio/issues/657
=> Introduce support for MeshCat viewer in RobotWrapper.

.ci-deps, .gitlab-ci.yml
Hi,
This PR updates gitlab-CI with a few things:
- run all tests in Debug and Release modes
- use [a special branch of robotpkg](https://gepgitlab.laas.fr/gepetto/robotpkg/tree/ci/pinocchio) in the docker image generation, that allows us to use hpp-fcl from source, and fix an issue in the main repo that prevented us to run the tests of the python bindings, for any version >= 1.3.4
- adds a (temporary) `.ci-deps` file, instructing the buildfarm to build the robotpkg package `path/hpp-fcl` (which has been updated in v1.0.1 in the branch for the previous point). We will remove this line from this file (and this file as it will be empty) when hpp-fcl v1.0.1 will be available in the binary repository
- take this file in account in the CI jobs
- set `CTEST_PARALLEL_LEVEL=4` to speed up tests a …
=> [CI] workaround the temporary lack of binary release of hpp-fcl

benchmark/CMakeLists.txt, benchmark/timings-cg.cpp, benchmark/timings-cholesky.cpp, benchmark/timings-derivatives.cpp, benchmark/timings-geometry.cpp, benchmark/timings-jacobian.cpp, benchmark/timings.cpp, bindings/python/algorithm/expose-frames.cpp, bindings/python/algorithm/expose-jacobian.cpp, bindings/python/pinocchio/deprecated.py, bindings/python/pinocchio/robot_wrapper.py, src/algorithm/frames.hpp, src/algorithm/frames.hxx, src/algorithm/jacobian.hpp, unittest/frames.cpp, unittest/python/bindings_dynamics.py
Mostly four things:
- Add a benchmark called `timings-jacobian` to compare between `getJointJacobian`, `computeJointJacobians` and related algorithms.
- Use the corresponding C++ function for the Python bindings of `jointJacobian`. Now, the signature and side-effects of `jointJacobian` in Python are completely aligned to C++. The old signature is now deprecated. This fixes #545
- Implemented missing `frameJacobian` function in C++, and use the newly-created function for the Python bindings of `frameJacobian`. The old signature is now deprecated. This also fixes #545
- Change the C++ return policy `getFrameVelocity` and `getFrameAcceleration`. Now, the value is returned instead of being written in a reference
=> Align Python Jacobian to C++, fix #545

doc/Doxyfile.extra.in, src/algorithm/aba.hpp, src/algorithm/check.hpp, src/algorithm/crba.hpp, src/multibody/joint/joint-base.hpp, src/multibody/joint/joint-composite.hpp, src/multibody/joint/joint-free-flyer.hpp, src/multibody/joint/joint-planar.hpp, src/multibody/joint/joint-prismatic-unaligned.hpp, src/multibody/joint/joint-prismatic.hpp, src/multibody/joint/joint-revolute-unaligned.hpp, src/multibody/joint/joint-revolute-unbounded.hpp, src/multibody/joint/joint-revolute.hpp, src/multibody/joint/joint-spherical-ZYX.hpp, src/multibody/joint/joint-spherical.hpp, src/multibody/joint/joint-translation.hpp, src/parsers/lua.cpp, src/utils/eigen-fix.hpp
This cleans the Doxygen output a bit by predefining a few macros during Doxygen parsing.
Also, I prefixed `PINOCCHIO_` to a few macros and changed the namespace `se3` to `pinocchio` in file [src/parsers/lua.cpp](https://github.com/stack-of-tasks/pinocchio/blob/devel/src/parsers/lua.cpp) (I don't know how ti was still `se3` in that file)
=> [doc] Doxygen and macros

src/multibody/liegroup/special-orthogonal.hpp
In log_SO2 (R), theta might be set to -PI and atan2 might return PI, if R is close to minus identity.
=> Make assertion more robust

bindings/python/algorithm/expose-com.cpp, src/algorithm/center-of-mass.hpp, src/algorithm/center-of-mass.hxx, unittest/com.cpp, unittest/python/bindings_com.py
Quite often, I find myself in need of just getting the total mass of the robot.
However, there is no simple one-shot algorithm to get it in Pinocchio.
The standard today is to check `data.mass[0]`. However, the only way of having the correct value is to first call an unrelated method which fills it as a side-effect, such as `centerOfMass`, possibly with meaningless arguments. This is annoying, and somewhat error-prone.
With this PR, I add an instance method `Model.getTotalMass()`.
I implemented it as an instance method inside the `Model` class because it is very simple, I did not know in which existing header to put it, and it seemed like an overkill to create a new one just for this.
I am returning the value, instead of putting it in `data.mass[0]`. This is partly due to the choice of …
=> [Model] Total mass

bindings/python/pinocchio/__init__.py
This fixes  #716 for python3 following the spirit of 8586c58a2362d56.
=> Fix python3 compatability for version number

bindings/python/algorithm/expose-com.cpp, src/algorithm/center-of-mass.hpp, src/algorithm/center-of-mass.hxx, src/multibody/data.hpp, unittest/com.cpp, unittest/python/bindings_com.py
Related to #724.
This PR adds an algorithm called `computeSubtreeMasses` which fills the whole `data.mass` vector.
An alternative implementation would be providing an optional boolean to `computeTotalMass(model,data)`, but I find the current interface is neater and clearer.
Also, I've exposed all missing overloads of `centerOfMass`.
=> [com] computeSubtreeMasses + CoM bindings

src/algorithm/center-of-mass.hxx
Correcting a bug introduced in #736
=> [computeSubtreeMasses] Fix bug for data.mass[0]

.ci-deps, .gitlab-ci.yml
This reverts commit eb73311af732c6efbbbeec4eade59f37cdc03ad9, because hpp-fcl v1 is in the binary respository now.
=> Revert "[CI] work with hpp-fcl v1, which is not yet in the binary repository"

src/multibody/model.hpp
A long time ago, I added the following lines in the constructor of Model:
```cpp
// Inertia of universe has no sense.
inertias[0].mass() = std::numeric_limits<Scalar>::quiet_NaN();
inertias[0].lever().fill (std::numeric_limits<Scalar>::quiet_NaN());
inertias[0].inertia().fill (std::numeric_limits<Scalar>::quiet_NaN());
```
While implementing #742, *I found a sense to the inertia of the universe* :)
When append modelB to joint a of modelA, the inertia of the universe of modelB ought to be added to the inertia of joint a. Sadly, the information was lost because it was initialized with NaN values.
=> Inertia of universe if initialized with Zero.

bindings/python/multibody/data.hpp, unittest/python/CMakeLists.txt, unittest/python/bindings_data.py
Allows to copy a `Data` object in Python by doing `data.copy()`.
=> [bindings] copyable data

src/algorithm/centroidal-derivatives.hxx, src/algorithm/rnea-derivatives.hxx, unittest/centroidal-derivatives.cpp
There is a small bug in the computation of dVdq and dAdq.
To explain using dVdq as the example, the computation of dVdq for the ith joint is given by ov[parent].cross(Ji), where Ji is the jacobian of the ith joint.
The current implementation of dVdq is done using dJ, which is ov[i].cross(Ji).
Normally, in most cases, the two are equal. The difference between the two is given by an S x S term, which is zero for all one DoF joint. And when we have a free flyer as the first joint, ov[parent] is zero, so we don't see the effect of S x S term again. This is why there are no problems with the unittest.
You can see the problem when you add a spherical joint ( or any joint in which SxS is not zero, such as freeflyer) at a position other than root joint. I added the spherical joint in …
=> Fix bug in computation of dVdq and dAdq

bindings/python/multibody/geometry-data.hpp
Allows to copy a `CollisionPair` object in Python by doing `pair.copy()`. Related to #764
=> [bindings] copyable collision pair

bindings/python/algorithm/expose-centroidal-derivatives.cpp, bindings/python/multibody/geometry-data.hpp, src/algorithm/centroidal-derivatives.hpp, src/algorithm/centroidal-derivatives.hxx, src/multibody/data.hpp, src/multibody/data.hxx, unittest/centroidal-derivatives.cpp
I extend the forceSet::motionAction to include the case when multiple column vectors are being applied to a single force vector.
Except that, the implementation is easy to understand.
=> add computation of dhg/dq inside computecentroidaldynamicsderivatives

src/algorithm/center-of-mass-derivatives.hxx, src/multibody/data.hpp
Number of operations are reduced and it also avoid memory allocations
=> algo/center-of-mass-derivatives: improve efficiency

bindings/python/algorithm/expose-aba-derivatives.cpp, bindings/python/multibody/data.hpp, bindings/python/multibody/expose-frame.cpp, bindings/python/multibody/expose-geometry.cpp, bindings/python/multibody/fcl/expose-fcl.cpp, bindings/python/multibody/frame.hpp, bindings/python/multibody/geometry-data.hpp, bindings/python/pinocchio/deprecated.py, bindings/python/spatial/expose-SE3.cpp, bindings/python/spatial/expose-force.cpp, bindings/python/spatial/expose-motion.cpp, bindings/python/utils/eigen_container.hpp, bindings/python/utils/handler.hpp, unittest/python/CMakeLists.txt, unittest/python/bindings_geometry_model.py
This PR is a follow-up of #782, containing all commits included in that PR except for one, which it was decided to discard.
It mainly on two additions to the bindings:
- Expose equality and inequality operators for `CollisionPair`
- Make the naming of std::vector bindings uniform. Before, as noticed in #555 and #626, some were named beginning with StdVec while others are with StdVect. Now they are all called StdVec. I retained the old StdVect as deprecated for back-compatibility.
=> [bindings] Expose equality-inequality for collision pairs + Uniform naming of StdVec

bindings/python/parsers/parsers.hpp, bindings/python/parsers/python.hpp, bindings/python/parsers/python/model.cpp, src/parsers/srdf.hpp, src/parsers/srdf.hxx, src/parsers/urdf.hpp, src/parsers/urdf/geometry.hxx, src/parsers/urdf/model.hxx, src/parsers/utils.hpp, src/serialization/archive.hpp, src/serialization/serializable.hpp
This PR removes the throw specifications that are deprecated since C++11:
`warning: dynamic exception specifications are deprecated in C++11 [-Wdeprecated]`.
=> remove deprecated throw specification

bindings/python/module.cpp, src/algorithm/frames.hxx, src/algorithm/jacobian.hxx, src/multibody/fwd.hpp, unittest/frames.cpp
This is to fix #773. 
This is NOT done yet but there are a few points I thought it's better to get feedback on earlier then later.
I haven't tested the code yet. The code compute the frame orientation I've copied from some other internal code we have, but I don't know if the jointJacobian code is working as expected.
A few things:
- Does the name `LOCAL_CARTESIAN_ORIENTED` make sense?
- I have to use a temporary `J_tmp` to avoid allocations (this was a problem we ran into with tsid). Though I am not 100% sure yet if using a local `J_tmp` and resizing works around the memory allocation problem. Does someone has an idea how to write the SE3 rotation of the jacobian without doing the `toActionMatrix() * J` matrix product - e.g. in a form where no new resulting matrix must be allocated and …
=> Add support for LOCAL_CARTESIAN_ORIENTED in jacobian computation

bindings/python/multibody/geometry-model.hpp, bindings/python/parsers/parsers.hpp, bindings/python/pinocchio/robot_wrapper.py, bindings/python/pinocchio/shortcuts.py, examples/python/collision-detection.py, unittest/python/bindings_geometry_object.py, unittest/python/bindings_geometry_object_urdf.py
This PR partially addresses #663 by providing convenience Python methods for creating models and geometry models in a single call, and analogously for the data objects.
This PR is autonomous, so if it is agreed upon it might be safely accepted. I thought it might be better to split the changes in two separate PRs so that this part may be more easily reviewed.
In summary:
- expose `buildGeomFromUrdf` accepting a single string for the package_directory, so we don't always have to put it inside a list
- define a function called `buildModelsFromUrdf` which parses an URDF and returns a Pinocchio Model plus one or two GeometryModel(s), depending on the inputs (see docstring for more details)
- define a Python method called `createData()` for `GeometryModel`, in analogy to `Model`
- define a …
=> [python] Define buildModelsFromUrdf and createDatas function

bindings/python/algorithm/expose-regressor.cpp, bindings/python/multibody/data.hpp, bindings/python/multibody/model.hpp, bindings/python/spatial/inertia.hpp, doc/treeview.dox, src/algorithm/regressor.hpp, src/algorithm/regressor.hxx, src/multibody/data.hpp, src/multibody/data.hxx, src/spatial/inertia.hpp, unittest/python/CMakeLists.txt, unittest/python/bindings_inertia.py, unittest/python/bindings_regressor.py, unittest/regressor.cpp, unittest/tspatial.cpp
Summary:
this PR introduces a joint torque regressor, such that
<a href="https://www.codecogs.com/eqnedit.php?latex=\tau&space;=&space;Y(q,\dot{q},\ddot{q})\pi" target="_blank"><img src="https://latex.codecogs.com/gif.latex?\tau&space;=&space;Y(q,\dot{q},\ddot{q})\pi" title="\tau = Y(q,\dot{q},\ddot{q})\pi" /></a>
where
<a href="https://www.codecogs.com/eqnedit.php?latex=\pi&space;=&space;(\pi_1^T\&space;\dots\&space;\pi_n^T)^T" target="_blank"><img src="https://latex.codecogs.com/gif.latex?\pi&space;=&space;(\pi_1^T\&space;\dots\&space;\pi_n^T)^T" title="\pi = (\pi_1^T\ \dots\ \pi_n^T)^T" /></a>
<a href="https://www.codecogs.com/eqnedit.php?latex=\pi_i&space;=&space;(m,&space;mc_x,&space;mc_y,&space;mc_z,&space;I_{xx},&space;I_{xy},&space;I_{yy},&space;I_{xz},&space;I_{yz},&space;I_{zz})^ …
=> Introduce joint torque regressor

unittest/aba-derivatives.cpp, unittest/contact-dynamics.cpp, unittest/frames.cpp
A few unit test contained some memory errors, as they where using uninitialized values.
These errors would not make the tests fail, but they caused valgrind to complain.
I fixed the errors. Now the tests are cleaner: in one case the input matrices where not set to zero and in another one a test was performed which did not make sense (the third error being negligible).
I would like to point out that valgrind complains a lot about python-parser-test too... However, since there is Python in the middle, it is much more difficult to analyze.
=> Fix memory errors in unit tests

bindings/python/pinocchio/deprecated.py
Fix a missing "pin." when calling computeJointJacobians(model,data,q)
=> python: fix missing pin.

src/algorithm/aba-derivatives.hpp, src/algorithm/aba-derivatives.hxx, src/algorithm/rnea-derivatives.hpp, src/algorithm/rnea-derivatives.hxx
Avoid useless memory allocation.
Related to #859 and #879.
=> algo/derivatives: use const references

doc/Doxyfile.extra.in, src/multibody/liegroup/special-euclidean.hpp, src/spatial/se3-base.hpp, unittest/liegroups.cpp
I propose to add a cheat sheet of notations used in Pinocchio. This is achieved by adding a doxygen command cheatsheet. Each function having a *remarkable identity* calls this command. This produces two things:
- in the menu on the left, there is a new page called *Cheat sheet*, containing something like:
- in function that have a *Remarkable identity*:
At the moment, I do not know how to somehow sort the elements of the cheat sheet.
=> [Doc] Add a cheat sheet

bindings/python/algorithm/expose-contact-dynamics.cpp, bindings/python/pinocchio/deprecated.py, src/algorithm/contact-dynamics.hpp, src/algorithm/contact-dynamics.hxx, unittest/contact-dynamics.cpp, unittest/python/bindings_dynamics.py
The previous implementation of `impulseDynamics` in Python did not allow to use signatures `impulseDynamics(model,data,v_before,J[,r_coeff[,inv_damping]])` directly and it required to set `q` to `None` in order to use it, as in `impulseDynamics(model,data,None,v_before,J,r_coeff,inv_damping)`.
Also, the argument overload was handled in `deprecated.py`, which is not the right place for this (it would have stopped working if the deprecated version had simply been removed).
I fixed it. Now all following 6 signatures are legal and recommended:
```
impulseDynamics(model,data,q,v_before,J)
impulseDynamics(model,data,q,v_before,J,r_coeff)
impulseDynamics(model,data,q,v_before,J,r_coeff,inv_damping)
impulseDynamics(model,data,v_before,J)
impulseDynamics(model,data,v_before,J,r_coeff) …
```
=> Fix Python impulseDynamics and modify dignature of forwardDynamics

package.xml, src/multibody/data.hpp
Allows to build Pinocchio inside a catkin workspace by cloning directly into it. This is intended to be used for the upcoming third-party library ROS-release deprecating the current catkinised wrapper [1].
[1] The catkinised wrapper was necessary as the Python installation directory was incorrect - since this has been fixed, we can replace the previous work-around wrapper simplifying maintenance and release.
=> Add package.xml

src/macros.hpp
This allows to avoid some borring warning from GCC
=> Change ordering of macros

bindings/python/pinocchio/rpy.py
Switching eigenpy to numpy array was breaking `rpyToMatrix`... The new code should work for both arrays and matrices.
I also modified `matrixToRpy`: it is now returning an object of the same type as the input.
These are hot fixes, but I think it would be nice in the future to implement these methods in C++.
Thanks @MedericFourmy for raising the issue
=> [python] [rpy] Fix for eigenpy arrays

.travis.yml, models/simple_humanoid.urdf, models/simple_humanoid_description/box.stl, src/parsers/urdf/geometry.hxx, unittest/urdf.cpp
This is an experimental features so I prefer not to document it.
It is experimental for the following reasons:
- it isn't tested a lot,
- it isn't benchmarked, i.e. for a collision pair (BVH with convex representation, Other), I don't know in which case the convex representation is preferable wrt the BVH representation.
- the API is not perfect yet and will likely change in the future.
=> [URDF][Experimental] Enable convex representation of meshes for collision detection

bindings/python/pinocchio/visualize/gepetto_visualizer.py, bindings/python/pinocchio/visualize/meshcat_visualizer.py, examples/CMakeLists.txt, examples/display_shapes.py, examples/gepetto-viewer.py, examples/meshcat-viewer-dae.py, examples/meshcat-viewer.py, examples/robot-wrapper-viewer.py, examples/sample-model-viewer.py, src/parsers/sample-models.hxx, unittest/python/bindings_geometry_object.py
I meant to wait for a day or two for further testing and/or additions in order to deliver these commits, but then I saw #1003, so I told myself I might as well do the PR now.
- Compared to #1003, I think my solution is slightly more robust to different install configurations (with/without hppfcl, mostly).
- Additionally, I fixed the visualization of geometric primitives for meshcat too
- I now use Talos in the visualization examples. previously this was not possible, since the model contained some primitives which made the visualizer crash.
- I retained the Romeo example in [meshcat-viewer-dae.py](https://github.com/stack-of-tasks/pinocchio/blob/a78eefc877f8dae19b5b07ddae372b5f4a520bb5/examples/meshcat-viewer-dae.py) to show the specific  problems that arise with DAE files in meshcat. I …
=> [visualize] Add geometric primitives

doc/b-examples/i-inverse-kinematics.md, examples/inverse-kinematics.cpp, examples/inverse-kinematics.py
Related to https://github.com/stack-of-tasks/pinocchio/pull/982#discussion_r355190193.
Following discussions with @nmansard, I found out why the example was not working for me without `Jlog`.
The problem is that the initial guess is `pinocchio.neutral(model)`, which is a singular configuration. Simple pseudo-inversion of the kinematic Jacobian kept it singular. Somehow, adding `Jlog` pulled the robot out of the singular configuration.
I have examined the problem carefully, and it does seem that `Jlog * err = err` and `pinv(Jlog) * err = err`, making the inclusion of `Jlog` useless for this particular case.
However, it seems that when the kinematic Jacobian `J` is singular, `pinv(Jlog * J) * err` and `pinv(J) * err` lead to different results. I am not sure wether this is a mathematical …
=> [examples/inverse-kinematics] Remove Jlog and use DLS instead

bindings/python/algorithm/expose-model.cpp, bindings/python/algorithm/expose-rnea.cpp, bindings/python/module.cpp, bindings/python/parsers/parsers.hpp, bindings/python/utils/pickle-vector.hpp, bindings/python/utils/std-aligned-vector.hpp, bindings/python/utils/std-vector.hpp, src/autodiff/casadi.hpp, unittest/python/CMakeLists.txt, unittest/python/bindings_rnea.py
This new feature avoids implementing dedicated signatures taking into account boost::python::list as argument
=> Add converter from Python list to std::vector<T>

bindings/python/pinocchio/robot_wrapper.py
Fixes #1035. @pFernbach The problem is not coming from Numpy but rather from bad calls.
=> Fix call to centroidalMomentum in RobotWrapper

bindings/python/fwd.hpp, bindings/python/math/expose-rpy.cpp, bindings/python/module.cpp, bindings/python/pinocchio/rpy.py, doc/treeview.dox, src/math/rpy.hpp, unittest/CMakeLists.txt, unittest/python/rpy.py, unittest/rpy.cpp
Related to #1026.
This implements `rpyToMatrix` and `matrixToRpy` in C++. They are available as C++ methods in the namespace `rpy`, and they are exposed in replacement to the old Python implementations.
This makes the behavior of the Python functions analogous to most other ones concerning the use of eigenpy.
I kept the old Python implementation for `npToTTuple`, `npToTuple` and `rotate`, for the following reasons:
- They already work well w.r.t. eignepy
- I don't think it makes sense to implement them in C++
- I had problems with creating the submodule `rpy` from C++
- I do not have time to do better than this right now and we want to have something acceptable as soon as possible :)
Concerning `rpyToMatrix`: I was amazed to see that a naive implementation employing the closed-form …
=> Implement rpy in C++

bindings/python/pinocchio/deprecated.py, bindings/python/pinocchio/explog.py, bindings/python/pinocchio/utils.py, unittest/python/CMakeLists.txt, unittest/python/bindings_fcl_transform.py, unittest/python/explog.py
Related to #1026.
This fixes module `explog` when a one-dimensional array is passed as input.
It also fixes `utils.isApprox` so that the following is true
```py
pinocchio.utils.isApprox(np.matrix([[0.], [1.], [2.]]), np.array([0., 1., 2.]))
```
In passing, I corrected the deprecation of `potentialEnergy` and `kineticEnergy`, and I fixed and added to the CI the unit test `bindings_fcl_transform.py`.
There are still a couple of things fo fix before closing #1026, most notably `utils.py` and `romeo_wrapper` (BTW, do we still need it?! Can't we just deprecated it?), plus a generalized double-check will be needed.
=> [python] Fix explog for input arrays

src/parsers/urdf/geometry.hxx
The only required element is that alpha which should not be 0.
=> [Minor] Change default material of collision object.

examples/codegen/codegen-crba.cpp, src/algorithm/energy.hxx, src/autodiff/cppad.hpp, src/codegen/cppadcg.hpp, src/spatial/explog.hpp
This PR introduces multiple fixes related to code-gen in pinocchio.
Most of the fixes are self-explanatory. The one which might require explanation is 82fac6182ff4367c6fb1ea1fb169f68eddb9df60
When calling `constant_pi<CppAD::...<Scalar> >`, boost calls the getter function as described in this doc https://www.boost.org/doc/libs/1_72_0/libs/math/doc/html/math_toolkit/new_const.html.
With the inheritence that is implemented, the getter returns PI of type double. As a result,  I get an error saying `cannot convert type 'double' into type CppAD::...<Scalar>`
82fac6182ff4367c6fb1ea1fb169f68eddb9df60 overloades the getter to return the correct type.
=> Multiple code-gen related fixes.

src/CMakeLists.txt
To let dependencies using `find_package(pinocchio)` get the installed include directory.
=> [CMake] export includes

bindings/python/pinocchio/visualize/gepetto_visualizer.py, bindings/python/pinocchio/visualize/meshcat_visualizer.py
Print a warning when the user tries to display a urdf containing  geometric primitives without HPP-FCL enabled.
See #1132
=> Python: warn user when trying to display geometric primitive without HPP-FCL

src/math/rpy.hpp, src/parsers/sample-models.hxx, unittest/rpy.cpp
The idea is to rely on Eigen's code which seems to be more numerically robust.
As future work, it would be necessary to adapt this code to handle Autodiff support.
=> Simplify RPY code

bindings/python/algorithm/expose-joints.cpp, src/algorithm/joint-configuration.hpp, src/algorithm/joint-configuration.hxx, src/fwd.hpp, src/multibody/liegroup/cartesian-product.hpp, src/multibody/liegroup/liegroup-algo.hxx, src/multibody/liegroup/liegroup-base.hpp, src/multibody/liegroup/liegroup-base.hxx, src/multibody/liegroup/special-euclidean.hpp, src/multibody/liegroup/special-orthogonal.hpp, src/multibody/liegroup/vector-space.hpp, src/spatial/act-on-set.hpp, src/spatial/explog.hpp, unittest/joint-configurations.cpp, unittest/liegroups.cpp
This PR fixes #1163 , for the time being.
Some API stuff in this PR:
1) the `dintegrate(...., ARG, OP)` user API
2) `enum AssignmentOperatorType` is moved from the pinocchio/spatial to pinocchio/fwd (to reside along with `enum ArgumentType`)
=> dIntegrate with ADDTO and RMTO assignment operators.

src/algorithm/joint-configuration.hpp, src/algorithm/joint-configuration.hxx, src/multibody/liegroup/cartesian-product.hpp, src/multibody/liegroup/liegroup-algo.hpp, src/multibody/liegroup/liegroup-algo.hxx, src/multibody/liegroup/liegroup-base.hpp, src/multibody/liegroup/liegroup-base.hxx, src/multibody/liegroup/special-euclidean.hpp, src/multibody/liegroup/special-orthogonal.hpp, src/multibody/liegroup/vector-space.hpp, unittest/joint-configurations.cpp
This PR adds the signature corresponding to transport of an input matrix along the manifold defined by the dIntegrate, as discussed in https://github.com/stack-of-tasks/pinocchio/issues/1163
=> dIntegrateTransport algorithm.

package.xml
This adds compatibility with Ubuntu 20.04 and distributions that default to Python 3.
Tested in a 20.04 CI. Does not work yet due to PkgConfig dependency for EigenPy in `bindings/python/CMakeLists.txt`.
=> package.xml: Prepare for Ubuntu 20.04 / Python3

bindings/python/pinocchio/visualize/panda3d_visualizer.py, examples/panda3d-viewer-play.py, examples/panda3d-viewer.py
Simple and efficient cross-platform visualizer based on [panda3d_viewer](https://github.com/ikalevatykh/panda3d_viewer).
This feature requires panda3d_viewer to be installed, this can be done using
`pip install --user panda3d_viewer`
=> Python bindings: add Panda3D based viewer

bindings/python/CMakeLists.txt, bindings/python/pinocchio/visualize/__init__.py, bindings/python/pinocchio/visualize/panda3d_visualizer.py, examples/panda3d-viewer-play.py
The title is self-explanatory :)
=> Fix panda3d installation and example

bindings/python/algorithm/expose-joints.cpp, src/algorithm/joint-configuration.hpp, src/multibody/liegroup/cartesian-product.hpp, src/multibody/liegroup/liegroup-base.hpp, src/multibody/liegroup/special-euclidean.hpp, src/multibody/liegroup/special-orthogonal.hpp, src/multibody/liegroup/vector-space.hpp, unittest/liegroups.cpp
Hi,
hpp-pinocchio doesn't compile on pinocchio 2.4.3, as `dIntegrate_dq` is called with 3 arguments, while 4 are expected.
@proyan : in #1163 you say "The default setting would be SETTO, so it doesn't affect existing code." and yet in #1169, all the methods get their prototype updated by one parameter addition without defaults.
Meaning the API has changed, doesn't it ?
And the [tests](https://github.com/stack-of-tasks/pinocchio/pull/1169/commits/17897a888a949cffad289803764d1cce0458f1e7#diff-4385ca28d5100ad9c49f0f0a6490ba24) have been updated, also meaning the API has changed. Otherwise, we should have kept the old tests with the old API, and added new tests, with the new API, side by side. Ensuring this wouldn't break existing code elsewhere, while the new features are available and …
=> fix API changes in #1169

src/algorithm/geometry.hxx, src/multibody/geometry.hpp, src/multibody/geometry.hxx
After playing around with hpp-fcl and pinocchio, I spent quite some time trying to figure out why collision checking was not working.
It was due to the fact the I modified a collision geometry in the model, with create a new geometry data. Thus the pointer stored in the collision object of geometry data was not pointing to the same object as the collision geometry in geometry model. I don't know if I was clear...
Anyway, the API of hppfcl allow to bypass completely the collision object class. As it avoids duplicating a pointer, I believe it is better not to use it. I don't think removing it completely is a good idea neither. So I open the debate.
=> Prefer not to use collisionObjects

bindings/python/multibody/geometry-object.hpp, bindings/python/pinocchio/visualize/gepetto_visualizer.py
With https://github.com/humanoid-path-planner/hpp-fcl/pull/167, compiled with qhull, and this PR, building a convex hull for a geometry in Pinocchio is as simple as:
```python
go = cmodel.geometryObjects[0]
go.geometry.buildConvexHull(False, None)
cgo = pinocchio.GeometryObject(go)
cgo.name = cgo.name + "_convex_hull"
cgo.geometry = go.geometry.convex
cmodel.addGeometryObject(cgo)
```
One can replace the current geometry with
```python
go = cmodel.geometryObjects[0]
go.geometry.buildConvexHull(False, None)
go.geometry = go.geometry.convex
```
=> [Python][gepetto-viewer] Enable display of convex object.

src/algorithm/model.hxx, src/multibody/model.hpp, src/multibody/model.hxx, src/parsers/urdf/model.hxx, unittest/frames.cpp, unittest/model.cpp, unittest/regressor.cpp
Closes #1199. Closes #1198 for the time being.
For in detail:
- remove assert that frame is found from `getFrameId` and include unit test to check it.
- modify return type of `addFrame`, `addBodyFrame` and `addJointFrame` to `FrameIndex` and remove all related warnings and useless casts
- additionally, change return type of `getBodyId` from `JointIndex` to `FrameIndex`. This has zero impact on the functionality of the code, because they are both typedefs of `size_t`, but it makes more sense from a documentation standpoint.
An observation about `addFrame`: the reason why the return type was `int` is that in the past the function used to return `-1` if there was already a frame with the same name but a different type. This was changed at commit 2f214472b0af1fd2039850b5c2984557073326de : …
=> Fix addFrame and getFrameId

package.xml
I didn't get any of the recent buildserver emails and we can't track down where they are getting lost... so changing my email for notifications.
=> Update my email since the robots.ox.ac.uk does not receive buildserver updates

package.xml
While this morning's documentation build job failure was unrelated, going through the logs highlighted a missing dependency: Adding this dependency will correctly render Latex in the future.
=> package.xml: Add texlive dependency for documentation jobs

bindings/python/multibody/model.hpp, src/algorithm/contact-dynamics.hpp, unittest/utils/macros.hpp
This PR resolves the remaining compiler warnings (multi-line comment and return cast type), cf. http://build.ros.org/job/Ndev__pinocchio__ubuntu_focal_amd64/18/gcc/ - and resolves the few "unstable" build warning emails every day :-).
Please let me know if there are better ways of doing this...
=> Address remaining compiler warnings

src/algorithm/model.hxx
I may be missing something, but that seems just a typo, that is however creating a compilation error in MSVC/v142.
=> model: Remove dot after literal string

src/algorithm/centroidal.hpp, src/algorithm/centroidal.hxx
CentroidalMomentum takes q, v as argument, and computes only `com`. Seems to be a missed opportunity.
=> [algorithm/centroidal] computeCentroidalMomentum calculates vcom as well

unittest/python/bindings_urdf.py
minor fix of:
```
…/pinocchio/unittest/python/bindings_urdf.py:23: ResourceWarning: 
unclosed file <_io.TextIOWrapper name='…/pinocchio/models/others/robots/romeo_description/urdf/romeo.urdf' mode='r' encoding='UTF-8'>
file_content = open(self.model_path,"r").read()
```
=> python unittest: use context to open files

bindings/python/algorithm/expose-joints.cpp, src/algorithm/joint-configuration.hpp, src/algorithm/joint-configuration.hxx, src/multibody/liegroup/cartesian-product-variant.hpp, src/multibody/liegroup/cartesian-product-variant.hxx, src/multibody/liegroup/cartesian-product.hpp, src/multibody/liegroup/liegroup-algo.hxx, src/multibody/liegroup/liegroup-base.hpp, src/multibody/liegroup/liegroup-base.hxx, src/multibody/liegroup/liegroup-variant-visitors.hpp, src/multibody/liegroup/liegroup-variant-visitors.hxx, src/multibody/liegroup/special-euclidean.hpp, src/multibody/liegroup/special-orthogonal.hpp, src/multibody/liegroup/vector-space.hpp, unittest/joint-configurations.cpp, unittest/liegroups.cpp, unittest/python/bindings_joints.py
Closes #1316.
I have implemented `isNormalized` for lie groups and for the joint configuration, with bindings.
I have very limited time, so I think I will let the bounds checks go for the time being. The normalization check has much more value and it is much more difficult to implement for an inexpert user, so I think this contribution is already important per se.
=> Add isNormalized

bindings/python/math/expose-rpy.cpp, src/math/rpy.hpp, src/math/rpy.hxx, unittest/python/rpy.py, unittest/rpy.cpp
This PR improves support for RPY by adding the following three functions:
- `rpyToJac`: Computes the Jacobian of the Roll-Pitch-Yaw conversion given the RPY angles, in reference frame either `LOCAL` or `WORLD`, defauting to `LOCAL`, plus `LOCAL_WORLD_ALIGNED` which is equivalent to `WORLD`
- `rpyToJacInv`: the inverse of such Jacobian, in given reference frame. I thought it might be faster and more stable next to singularities with respect to directly computing the inverse, but in practice I did not find a huge difference
- `rpyToJacDerivative`, time derivative of such Jacobian, given the RPY angles and their time derivative, in given reference frame.
All functions have python bindings.
- `rpyToJac` is tested against identity at RPY=0, for relationship between different frames, against …
=> Improve support for rpy

bindings/python/multibody/data.hpp
I noticed that `Data.g` was not exposed.
Also, `Data.C` was exposed _twice_. This did not seem to have any negative effects except that the docstring of the first exposition was overridden by the second one, which was less exhaustive.
I fixed both problems, along with a minor formatting issue of an unrelated docstring
=> [bindings] Expose g and avoid double exposition of C

src/spatial/explog.hpp, unittest/explog.cpp
When rendered, this adds to doc of `Jlog6`:
=> [Doc] Add remarkable identities for Jlog6

src/algorithm/model.hpp, src/algorithm/model.hxx, unittest/model.cpp
The parent frame of the geometry objects was copied from the input model. As the frame order is not kept, they were erroneous.
As a side note, I think the frame order could be kept. I won't have time to dig into this.
=> Fix buildReducedModel

bindings/python/pinocchio/visualize/meshcat_visualizer.py
- Adds meshcat capsule visualisation as a triangulated mesh.
- Requires meshcat-python 0.19 or newer.
- Reverts to displaying a cylinder on older versions of meshcat-python.
=> Meshcat capsule visualisation

bindings/python/algorithm/expose-model.cpp, bindings/python/pinocchio/robot_wrapper.py, examples/build-reduced-model.py, src/algorithm/model.hpp, src/algorithm/model.hxx, unittest/model.cpp
This was referenced in https://github.com/stack-of-tasks/pinocchio/issues/1423.
Summary:
- Extended `buildReducedModel` ([here](https://github.com/ntorresalberto/pinocchio/blob/106ebe56a879d99c1b300318dbea4a027773b132/src/algorithm/model.hxx#L498)) to take multiple GeometricModels (`std::vector<GeometricModel>`) as input. Now the old `buildReducedModel` ([here](https://github.com/ntorresalberto/pinocchio/blob/106ebe56a879d99c1b300318dbea4a027773b132/src/algorithm/model.hxx#L475)) function is redirected to this one to avoid redundant code.
- Exposed the new function as `pinocchio.buildReducedModel` in python (that takes and returns a list of GeometricModel).
- Added `RobotWrapper.reduceModel` function that uses the new `buildReducedModel`. 
I did it so `list_of_joints_to_lock` can take a …
=> add Robot wrapper.reduceModel function and extend buildReducedModel for multiple GeometricModel

unittest/liegroups.cpp
fix on Boost 1.76:
```
/src/pinocchio/unittest/liegroups.cpp:455:23: error: no template named 'vector' in namespace 'boost::mpl'
typedef boost::mpl::vector<  VectorSpaceOperationTpl<1,Scalar,Options>
~~~~~~~~~~~~^
/src/pinocchio/unittest/liegroups.cpp:479:23: error: no template named 'vector' in namespace 'boost::mpl'
typedef boost::mpl::vector<  VectorSpaceOperationTpl<1,Scalar,Options>
~~~~~~~~~~~~^
/src/pinocchio/unittest/liegroups.cpp:506:23: error: no template named 'vector' in namespace 'boost::mpl'
typedef boost::mpl::vector<  VectorSpaceOperationTpl<1,Scalar,Options>
~~~~~~~~~~~~^
/src/pinocchio/unittest/liegroups.cpp:530:23: error: no template named 'vector' in namespace 'boost::mpl'
typedef boost::mpl::vector<  VectorSpaceOperationTpl<1,Scalar,Options>
~~~~~~~~~~~~^
```
=> [Tests] add missing include

package.xml, src/utils/file-explorer.cpp, src/utils/file-explorer.hpp
I've also run into the issue described by @jmirabel in #1463. The following work-around resolves this issue (as postulated at in https://github.com/stack-of-tasks/pinocchio/issues/1463#issuecomment-872225739). 
Note, this is likely not Windows-compatible due to the forward slash "/". I'd love to hear some thoughts/discussion on a better solution for this issue
@jmirabel - would this PR solve your issue as well?
=> Work-around for finding meshes of URDFs in ROS devel spaces #1463

bindings/python/pinocchio/visualize/meshcat_visualizer.py, src/parsers/urdf/geometry.cpp
BVH models should be loaded in a raw manner after checking if they are not related to a specific file
=> meshcat: fix loading of BVH model

examples/inverse-kinematics.cpp
Simple PR to change:
- `typedef` to `using` when defining the Vector6d, as there are advantages to the `using` syntax: https://stackoverflow.com/a/32959200
- Add some curly braces to the success/failure scenarios, as adding further statements after these tripped me up in the same way as: https://stackoverflow.com/a/2125078
=> Change 'typedef' to 'using', add curly braces

bindings/python/parsers/sdf/geometry.cpp, bindings/python/parsers/sdf/model.cpp, bindings/python/pinocchio/robot_wrapper.py, bindings/python/pinocchio/shortcuts.py, bindings/python/pinocchio/visualize/meshcat_visualizer.py, bindings/python/utils/pickle-vector.hpp, src/algorithm/centroidal-derivatives.hxx, src/parsers/sdf.hpp, src/parsers/sdf/geometry.hxx, src/parsers/urdf/geometry.hxx, unittest/centroidal-derivatives.cpp
This PR fixes some issues in sdf parsing related to non-existent geometry models, and adds signatures in python and c++ for loading geometry models. Also it links with https://github.com/Gepetto/example-robot-data/pull/100 to support easy loading of cassie model through robot_wrapper.
In addition, this PR adds the bug fix in centroidal-dynamics-derivatives from 2.6.3, and the rest of the commits from 2.6.3, and thus sits on top of 2.6.3.
=> Add signatures for loading geometry models, add support in robot_wrapper, and fix issues in sdf parsing

bindings/python/pinocchio/visualize/base_visualizer.py, bindings/python/pinocchio/visualize/meshcat_visualizer.py
This commit adds a `captureImage()` method for visualizers. It returns an RGB array. A minimal example:
```python
import matplotlib.pyplot as plt
visualizer.display(q)
img: np.ndarray = visualizer.captureImage()
plt.imshow(img)
plt.axis('off')
plt.show()
```
For now, it is only implemented for `MeshcatVisualizer`. This requires that rdeits/meshcat-python#93 be merged first. To work, this requires the visualizer window be already opened in the browser.
I also added an optional argument `capture` to the `play()` method. It makes the method return a list of ndarrays containing each captured image, which can be fed to something like `imageio` to produce an MP4 video.
=> [visualize] captureImage() method

.gitmodules, benchmark/timings-geometry.cpp, examples/capsule-approximation.py, examples/codegen/codegen-crba.cpp, examples/panda3d-viewer-play.py, examples/panda3d-viewer.py
Hi,
Running all tests on a clean repo `clone --recursive` currently fails with:
```cpp
120/147 Test #147: example-cpp-codegen-crba ...........................Child aborted***Exception:   0.16 sec
Opening file: /pinocchio/models/others/robots/ur_description/urdf/ur5_robot.urdf
Error:   File /pinocchio/models/others/robots/ur_description/urdf/ur5_robot.urdf does not exist
at line 55 in /build/urdfdom-VnCcob/urdfdom-1.0.4+ds/urdf_parser/src/model.cpp
terminate called after throwing an instance of 'std::invalid_argument'
what():  The file /pinocchio/models/others/robots/ur_description/urdf/ur5_robot.urdf does not contain a valid URDF model.
```
It looks like this folder was changed in https://github.com/stack-of-tasks/pinocchio/commit/8b0d1471b1fa5097acde159e9cf3146c45270cdc , but not …
=> fix module name

doc/d-practical-exercises/3-invkine.md, doc/d-practical-exercises/src/mobilerobot.py
Hello. I try to do this exercise, but noticed that there are a lot of deprecated or not working function. 
class mobileRobotWrapper not working, and I don't know how to fix it, so I remove it.
=> Update old function, remove mobile robot wrapper

src/utils/file-explorer.cpp, src/utils/file-explorer.hpp
This PR appends the suffix "/share" to the list of directories loaded by AMENT_PREFIX_PATH. It fixes https://github.com/stack-of-tasks/pinocchio/issues/1520
=> Append "/share" to AMENT_PREFIX_PATH

README.md, bindings/python/algorithm/expose-joints.cpp, unittest/python/bindings_joint_algorithms.py
As mentioned in #1571, this PR exposes the `dIntegrateTransport` function from the `pinocchio` namespace to the Python bindings.
I also added a unittest for good measure.
=> Expose dIntegrateTransport

benchmark/timings-cholesky.cpp, benchmark/timings-derivatives.cpp, benchmark/timings-geometry.cpp, benchmark/timings-jacobian.cpp, benchmark/timings-parallel.cpp, benchmark/timings.cpp
Reduces the allocations in the finite-difference baselines by passing the output argument to `pinocchio::integrate`. Also uses the `PINOCCHIO_ALIGNED_STD_VECTOR` macro in the benchmarks.
=> [timings] Reduce allocations in finite-difference baselines

src/algorithm/compute-all-terms.hxx
This commit adds a missing noalias operator which resulted in tempory
allocations when running computeAllTerms. Eliminating the temporary
allocation results in a ~11% speed-up when performing computeAllTerms.
Timings from timings.cpp, compiled with Clang++12 (Ubuntu 20.04 stock-Eigen):
Before: 15.6495us
After: 13.8686us
=> [computeAllTerms] Add missing noalias to avoid temporary allocation

src/multibody/model.hxx
fix for #1581 .
Throws when incorrect joint parent id is given
=> [multibody/model] add joint arg validation

src/multibody/geometry.hpp, src/multibody/geometry.hxx, unittest/geom.cpp
Add a test to check object removal and correct collision pair handling.
This partially fixes https://github.com/stack-of-tasks/pinocchio/issues/1587 by not requiring the user to manipulate GeometryObject instances by himself.
=> [multibody/geometry] Add method to remove an object.

CMakeLists.txt, package.xml
HPP-FCL is now available on `testing` for ROS Noetic, with a release to Melodic pending. We can now start targeting Pinocchio binaries with HPP-FCL included.
This PR also introduces an ament integration for ROS2 releases.
=> Support HPP-FCL for ROS binaries & introduce ROS2 ament integration

.github/workflows/conda/conda-env.yml, .github/workflows/macos-linux-conda.yml, src/algorithm/contact-dynamics.hpp
The linebreak in the equations triggers a multi-line comment through the backslash as the final character. Using the no-op `{}` fixes the problem.
=> Avoid triggering multi-line comment in Latex formula

src/multibody/geometry.hpp, src/multibody/geometry.hxx, src/parsers/urdf/geometry.cpp
While I am aware behind the rationale of twinning HPP-FCL v2 with Pinocchio v3 for C++11 reasons in binary builds, there does not appear to be anything holding back using the latest HPP-FCL v2 in source builds with the Pinocchio devel branch. This PR fixes the one pointer issue and enables Pinocchio v2/devel to be compatible with either HPP-FCL v1 or v2.
=> Make Pinocchio v2 compatible with HPP-FCL v2

bindings/python/pinocchio/visualize/meshcat_visualizer.py, examples/CMakeLists.txt, examples/collision-with-point-clouds.py
=> Add example of collision with a point cloud

.github/workflows/conda/conda-env.yml, bindings/python/multibody/geometry-object.hpp
Hi,
Following #1631, we should be able to use hpp-fcl v2, but this raise the following issue on various linux:
```python 
133/134 Test #133: example-py-collision-with-point-clouds .............***Failed    1.27 sec
Traceback (most recent call last):
File "…/pinocchio/examples/collision-with-point-clouds.py", line 70, in <module>
go_panda_hand.geometry.buildConvexRepresentation(False)
TypeError: No to_python (by-value) converter found for C++ type: boost::shared_ptr<hpp::fcl::CollisionGeometry>
```
The CI can reproduce it, as shown in this PR.
=> follow up on hpp-fcl v2

bindings/python/pinocchio/visualize/base_visualizer.py, bindings/python/pinocchio/visualize/rviz_visualizer.py
Method `play()` overridden, `Qtest.qWait()` used for the delay between one display to another instead of `time.sleep()`.
In the original implementation method `play()` form base_visualizer was used.
=> Fix method play() of rviz_visualizer

src/multibody/liegroup/special-orthogonal.hpp, src/spatial/explog-quaternion.hpp, unittest/joint-configurations.cpp, unittest/liegroups.cpp
It seems that using quaternion multiplication (`q0.conjugate()*q1`) then converting to matrix is actually more accurate than using matrix multiplication (`q0.matrix().transpose()*q1.matrix()`) in calculating the difference between `q1` and `q0`. 
When two SO3 configurations are very similar, with coordinates differing approximately by the smallest floating point division for `double` (I checked this using `numpy.spacing(value)` for the `numpy.float64` value of the quaternion coordinate), quaternion multiplication followed by converting to matrix gives a non-identity result (non-zero distance) while the matrix conversion followed by matrix multiplication gives an identity matrix.
=> SO3 diff impl use quaternion instead of rotation matrix

.github/workflows/ros-ci.yml
WIP - testing branch to prepare a ROS2 release
=> ROS2 release support

models/simple_humanoid_rel_mesh.urdf, src/parsers/utils.hpp, unittest/urdf.cpp
Currently, we cannot import a urdf that specifies a relative mesh path without using `//package`, see https://github.com/stack-of-tasks/pinocchio/issues/1741.
=> Fix relative path in urdf

src/parsers/utils.hpp, unittest/urdf.cpp
this solves #1747.
We are now handling not only `./rel-mesh-path` but also `rel-mesh-path` and `../rel-mesh-path`.
=> URDF: fix loading relative mesh path in urdf

bindings/python/multibody/joint/joint-derived.hpp, bindings/python/multibody/joint/joint.hpp, bindings/python/multibody/model.hpp, src/multibody/joint/joint-basic-visitors.hpp, src/multibody/joint/joint-basic-visitors.hxx, src/multibody/joint/joint-composite.hpp, src/multibody/joint/joint-free-flyer.hpp, src/multibody/joint/joint-generic.hpp, src/multibody/joint/joint-mimic.hpp, src/multibody/joint/joint-model-base.hpp, src/multibody/joint/joint-planar.hpp, src/multibody/joint/joint-prismatic-unaligned.hpp, src/multibody/joint/joint-prismatic.hpp, src/multibody/joint/joint-revolute-unaligned.hpp, src/multibody/joint/joint-revolute-unbounded-unaligned.hpp, src/multibody/joint/joint-revolute-unbounded.hpp, src/multibody/joint/joint-revolute.hpp, src/multibody/joint/joint-spherical-ZYX.hpp, src/multibody/joint/joint-spherical.hpp, src/multibody/joint/joint-translation.hpp, src/multibody/model.hpp, src/multibody/model.hxx, src/serialization/model.hpp, unittest/model.cpp
- every joint returns a vector of boolean of size nq describing if each of the DOF has bounds or not
- model: vector stacking the boolean vector of configurations limits of each joint in the model
now we can do:
```
In [1]: import pinocchio as pin
...: model = pin.Model()
...: model.addJoint(0, pin.JointModelFreeFlyer(), pin.SE3.Identity(), "root_joint")
...: model.addJoint(0, pin.JointModelRZ(), pin.SE3.Identity(), "joint1")
...: model.addJoint(0, pin.JointModelRUBZ(), pin.SE3.Identity(), "joint2")
...: model.configurationLimit.tolist()
Out[1]: [True, True, True, False, False, False, False, True, False, False]
```
which can be used to see where bounds are expected or not using e.g. `model.upperPositionLimit[model.configurationLimit.tolist()]` and check if these are meaningful joint …
=> Configuration limits for joints and model

bindings/python/CMakeLists.txt, src/multibody/liegroup/liegroup-base.hpp, src/multibody/liegroup/liegroup-generic.hpp, src/multibody/liegroup/vector-space.hpp, unittest/python/pybind11/CMakeLists.txt
Speed-up when not building tests should be ~30% by conditionally compiling `cpp2pybind11` following the same logic as `add_unit_test`
=> Address remaining warnings + speed-up build for BUILD_TESTING=OFF

README.md
All builds of ROS2 are now passing and will be available upon the next sync. To access their status more easily, this adds the badges from CI to the README alongside additional information on how to use it in projects.
=> Add status of ROS builds to README

bindings/python/pinocchio/visualize/meshcat_visualizer.py, examples/display-shapes-meshcat.py
Add support for cone shape in Meshcat dispaly, which is discussed in #1768 .
=> pinocchio/visualize: Add support for cone shape in meshcat dispaly

.github/workflows/macos-linux-conda.yml, src/multibody/model.hxx, unittest/models/link_and_joint_identical_name.urdf, unittest/urdf.cpp
A sufficient solution is to elevate the assertion to an exception 
Fixes #1771
=> Elevate check for ambiguous input argument to an exception

src/algorithm/geometry.hxx, unittest/geom.cpp
The change comes with a unit test which was failing before and which is self-explanatory.
=> Skip collision pairs between geom on same joint in appendGeometryModel

bindings/python/algorithm/expose-frames.cpp, src/algorithm/frames.hpp, src/algorithm/frames.hxx, unittest/frames.cpp
Hello,
Following my discussion with @jcarpent, I propose the implementation of 3 new helper functions that compute supported inertia and force by frames.
Motivation : 
In our current robot setup, we have a force-torque sensor mounted in the arm. We would like to compute the forces that this sensor is supposed to measure.
Problem : 
This sensor is represented by a FIXED_JOINT in the urdf, thus it is not represented in the pinocchio model, and retrieving such info is not straightforward. 
Solution :
The method `pinocchio::computeFrameSupportedForce` compute this force. It takes into account inertial forces, gravity and external forces.
Computing supported inertias is an intermediary step in that process. I choose to expose it, as it may be useful for other uses.
=> Add helper functions for computing supported inertia and force by frames

src/algorithm/frames.hxx, unittest/frames.cpp
Hello,
The [previous PR](https://github.com/stack-of-tasks/pinocchio/pull/1796) has been merged before I address all the remarks.
So this PR solves it : 
- It fixes a minor bug in the computation on the inertia with subtree
- It removes the dependency to urdfdom for the test (as mentioned here https://github.com/stack-of-tasks/pinocchio/pull/1796#discussion_r1030590778)
=> Follow-up : Supported inertia by frame

.github/workflows/ros-ci.yml, src/multibody/liegroup/special-euclidean.hpp, unittest/liegroups.cpp
I don't think it would impede performance much since quaternions are fixed-size but you probably know better than me.
=> Error when integrating SE3 with the same vector given as input and output

bindings/python/pinocchio/visualize/base_visualizer.py, bindings/python/pinocchio/visualize/meshcat_visualizer.py, examples/meshcat-viewer.py
This PR adds new features to the Python visualization API, and implements them for MeshcatVisualizer
+ add visualizer methods for setting the camera target, position,
environment background color
+ base class raises NotImplementedError when there is no implementation
*Note* This PR is a backport from changes added to Pinocchio 3.
=> [python/visualize] Extend visualizer features and implement them for MeshcatVisualizer

examples/inverse-kinematics.py
The previous target was unfeasible, so CLIK would never converge. It converges with this one.
=> Fix IK example

bindings/python/multibody/joint/joint-derived.hpp, bindings/python/multibody/joint/joint.hpp
Following the discussion of issue #802, this PR presents an update to the documentation of the `shortname` function for the python class `JointModel` exposed by Boost.python.
This function is the only way to determine the joint type in python and was previously left undocumented.
The new function documentation describes the following possible cases:
>>>
- JointModelR[*]: Revolute Joint, with rotation axis [*] ∈ [X,Y,Z]
- JointModelRevoluteUnaligned: Revolute Joint, with rotation axis not aligned with X, Y, nor Z
- JointModelRUB[*]: Unbounded revolute Joint (without position limits), with rotation axis [*] ∈ [X,Y,Z]
- JointModelRevoluteUnboundedUnaligned: Unbounded revolute Joint, with rotation axis not aligned with X, Y, nor Z
- JointModelP[*]: Prismatic Joint, with rotation axis [*] ∈ …
=> Update documentation of `JointModel.shortname` in python bindings

examples/CMakeLists.txt
so don't activate it for python 2
```
$ rg ' @ ' -tpy
examples/static-contact-dynamics.py
100:ls = np.linalg.pinv(Jc__feet_bl_T) @ g_bl  # This is (3)
131:tau = g_j - Jc__feet_j_T @ ls
```
=> CMake: an example require python 3

doc/c-maths/a-rigid-bodies.md, doc/d-practical-exercises/1-directgeom.md, doc/d-practical-exercises/2-invgeom.md
A handful of updates to the documentation to get rid of deprecated python commands etc., a few grammar fixes, missing packages etc.
=> Documentation 

.github/workflows/macos-linux-conda.yml, bindings/python/utils/copyable.hpp, unittest/python/bindings_SE3.py
Pickable is the worst solution for enabling an object to be copyable. Instead, the purpose solution is better while still keeping the pickability of the Pinocchio objects.
Additionally, the pickable solution creates segfaul in my Apple M1 chip. But, if I remember correctly, this doesn't happen in Ubuntu.
In short this PR enables us to do the following:
```python
import pinocchio
import copy
model = pinochio.Model()
m1 = copy.copy(model)
m2 = copy.deepcopy(model)
```
=> Enabled copy and deepcopy

src/parsers/sample-models.hxx
This PR addresses the issue #2042.
=> parsers/sample: Renamed freeflyer_joint to root_joint

examples/inverse-dynamics.cpp, examples/inverse-dynamics.py
Follow up to the [2 DoF gravity compensation](https://www.youtube.com/watch?v=jCM1n39dDWk) tutorial, where it was mentioned that a simple ID example was missing. Thanks @jpieper!
=> Add inverse dynamics examples

examples/panda3d-viewer-play.py, examples/panda3d-viewer.py
Related to #1991, this PR fixes the two examples of using Panda3D for visualization.
=> Fixed outdated Panda3D examples

.github/workflows/check-changelog.yml, CHANGELOG.md
Add a changelog inspired by https://keepachangelog.com/en/1.1.0/
=> Add changelog

CHANGELOG.md, include/pinocchio/math/fwd.hpp
Add direct import of boost header containing `boost::math::is_floating_point` to avoid import error:
```
In file included from bazel-out/k8-opt/bin/external/com_github_stack_of_tasks_pinocchio/_virtual_includes/pinocchio/pinocchio/math/quaternion.hpp:12,
from bazel-out/k8-opt/bin/external/com_github_stack_of_tasks_pinocchio/_virtual_includes/pinocchio/pinocchio/spatial/se3-tpl.hpp:12,
from bazel-out/k8-opt/bin/external/com_github_stack_of_tasks_pinocchio/_virtual_includes/pinocchio/pinocchio/spatial/se3.hpp:44:
bazel-out/k8-opt/bin/external/com_github_stack_of_tasks_pinocchio/_virtual_includes/pinocchio/pinocchio/math/fwd.hpp:16:54: error: expected template-name before '<' token
16 |   struct is_floating_point : boost::is_floating_point<T>
| …
```
=> Add direct boost is_floating_point import

CHANGELOG.md, bindings/python/pinocchio/visualize/meshcat_visualizer.py, examples/meshcat-viewer.py, include/pinocchio/bindings/python/multibody/geometry-object.hpp, include/pinocchio/multibody/fcl.hpp, unittest/python/bindings_build_geom_from_urdf_memorycheck.py, unittest/python/bindings_geometry_object.py
This PR solve #2084.
I have added `GeometryObject::meshMaterial` attribute to store different kind of material with a boost::variant.
Right now, only two material type exists : GeometryNoMaterial and GeometryPhongMaterial.
But more complex ones can be added in the future.
The boost::variant Python binding is working well and can maybe be ported to manage the `Model::joints`.
`meshcat_visualizer.py` use this new feature BUT [meshcat-python Phong material](https://github.com/meshcat-dev/meshcat-python/blob/785bc9d5ba6f8a8bb79ee8b25f523805946c1fbd/src/meshcat/geometry.py#L185) is not implemented.
I had to patch my meshcat-python to be able to display specular et emissive light.
Before merging I have to add an example but I would like to have a technical review before going further.
=> Add material to GeometryObject

CHANGELOG.md, include/pinocchio/algorithm/crba.hxx, unittest/crba.cpp
=> Fix malloc issue in CRBA

CHANGELOG.md, examples/floating-base-velocity-viewer.py
After several questions/discussions (e.g. #1657, #1357, #1137, #1122) about the conventions used for the velocity vector for different joints that can serve as a floating base, I started a small script to verify. 
This script builds a simple robot that is just a box with dimensions x=0.8, y=0.4, z=0.2. The floating base can be set to either `JointModelFreeFlyer`, `JointModelSphericalZYX` or `JointModelSpherical`. It prints several properties of the mode, increments each velocity component by 1, calculates the resulting `a`, `v_next`, `q_next` via `pin.aba` and visualizes the integrated configuration q_next via MeshCat. 
This could be useful for people who want to try it out for themselves. Also, we could add more joints in the future to test them as well.
=> Add example to visualize floating base velocity

CHANGELOG.md, bindings/python/pinocchio/visualize/meshcat_visualizer.py
Closes https://github.com/stack-of-tasks/pinocchio/issues/2146
=> Don't iterate on collision geometries when undefined

CHANGELOG.md, include/pinocchio/multibody/liegroup/special-euclidean.hpp, include/pinocchio/multibody/liegroup/special-orthogonal.hpp, include/pinocchio/multibody/liegroup/vector-space.hpp
Call `pinocchio::isNormalized` intead of `isNormalized` that it seen ambiguous by MSVC (LieGroupBase or namespace).
Close #2154
=> Fix ambiguous function call on Windows

CHANGELOG.md, include/pinocchio/algorithm/model.hxx, unittest/model.cpp
Fix for frames list order when building a reducedModel. 
Fix the problem  in the geometryReduced Model mentioned in  #2158 .
=> Fix Frames order in reducedModel

.github/workflows/macos-linux-conda.yml, .github/workflows/windows-conda.yml, CHANGELOG.md, bindings/python/CMakeLists.txt
=> Fix python stub generation

CHANGELOG.md, include/pinocchio/algorithm/frames.hpp
See https://github.com/stack-of-tasks/pinocchio/discussions/2168
=> Add remark on getFrameClassicalAcceleration

CHANGELOG.md, include/pinocchio/algorithm/jacobian.hpp
After several discussions about Jacobians and ReferenceFrames, and the nice improvement of the doc string #2190, I propose to fix and improve the docstring of `getJointJacobian`.
This doc string did not render properly due to some missing `\f` in front of `$`. While adding it, I tried to add further details about the calculated quantities and be verbose about their meaning.
For more rigorous mathematical details, we could also refer to [A Mathematical Introduction to Robotic Manipulation](https://www.cse.lehigh.edu/~trink/Courses/RoboticsII/reading/murray-li-sastry-94-complete.pdf) by Murray, Li and Sastry (thanks for the pointer @stephane-caron).
=> [doc] Improve documentation of getJointJacobian.

CHANGELOG.md, doc/a-features/e-lie.md, doc/c-maths/a-rigid-bodies.md
Just noticed this:
> ![image](https://github.com/stack-of-tasks/pinocchio/assets/1189580/d447949b-4874-47e1-9aa2-42642f022c18)
Also using this opportunity to fix the reference below :wink:
=> Fix SO(3) title and ref in the documentation

CHANGELOG.md, include/pinocchio/algorithm/model.hpp, include/pinocchio/algorithm/model.hxx, include/pinocchio/multibody/model.hpp, unittest/model.cpp
This modification follows https://github.com/stack-of-tasks/pinocchio/discussions/2203.
In the new version, when appending model B to model A on frame F, joints are copied in the
following order
- joints of model A up to the parent of F,
- all the descendents of parent of F,
- the remaining joints of A.
=> Modify model appending algorithm

.pre-commit-config.yaml, CHANGELOG.md, src/parsers/mjcf/mjcf-graph.cpp
=> Fix compilation issue for Boost 1.85

unittest/python/bindings_build_geom_from_urdf_memorycheck.supp
To fix packaging on ArchLinux, when valgrind is installed.
They are the same as the 2 previous ones, except:
- realloc instead of alloc
- some extra `fun:UnknownInlinedFun`
=> unittest: add 2 valgrind suppressions

CHANGELOG.md, bindings/python/algorithm/expose-contact-inverse-dynamics.cpp, bindings/python/algorithm/expose-model.cpp, bindings/python/algorithm/expose-rnea.cpp, unittest/python/CMakeLists.txt, unittest/python/bindings_contact_inverse_dynamics.py
In a similar way to the [cpp test](https://github.com/stack-of-tasks/pinocchio/blob/master/unittest/contact-inverse-dynamics.cpp#L82) for the `contactInverseDynamics` function, I propose to add a python test and check if this function is usable from Python. 
the c++ function requires for the contact models, data and cones
```
contactInverseDynamics(..., 
const std::vector<RigidConstraintModelTpl<Scalar, Options>, ConstraintModelAllocator> & contact_models,
std::vector<RigidConstraintDataTpl<Scalar, Options>, ConstraintDataAllocator> & contact_datas,
const std::vector<CoulombFrictionConeTpl<Scalar>, CoulombFrictionConelAllocator> & cones,
```
and this works well when constructing them as `StdVec_RigidConstraintData()` and then appending contact data here (see test1). However, if you try to …
=> add python test for `contactInverseDynamics`

CHANGELOG.md, CMakeLists.txt
This already had been fixed in 4d521ec but had been lost in CMakeLists refactoring.
=> Turn `BUILD_WITH_LIBPYTHON` OFF when building with PyPy

CHANGELOG.md, unittest/liegroups.cpp, unittest/python/bindings_liegroups.py
Hi, I propose adding another test for the `dIntegrateTransport` function to check its "inverse" by using the reverse path. I use this function for vector transport along different manifolds.
=> Test vector transport and its inverse with `dIntegrateTransport`

CHANGELOG.md, README.md, bindings/python/algorithm/expose-regressor.cpp, include/pinocchio/algorithm/regressor.hpp, include/pinocchio/algorithm/regressor.hxx, include/pinocchio/algorithm/regressor.txx, include/pinocchio/bindings/python/multibody/data.hpp, include/pinocchio/multibody/data.hpp, include/pinocchio/multibody/data.hxx, src/algorithm/regressor.cpp, unittest/regressor.cpp
Hello Pinocchio team!
I am pleased to use your library and apply it for system identification purposes. I have found much useful `jointTorqueRegressor` and wanted to contribute by implementing `kineticEnergyRegressor` and `potentialEnergyRegressor`.These functions are alike `jointTorqueRegressor` show a linear connection from dynamical parameters to dynamical quantity.
I have added tests and documentation up to my capability. 
Please let me know your thoughts, I am open for modifications and there are more ideas on possible contribution I am willing to implement later.
=> Kinetic and potential energy regressors

CHANGELOG.md, CMakeLists.txt, bindings/python/CMakeLists.txt, unittest/python/CMakeLists.txt
Pinocchio Python binding needs hpp-fcl Python binding for collision/contact related algorithms.
We allow with the `BUILD_WITH_HPP_FCL_PYTHON_BINDINGS` CMake variable to build Pinocchio C++ library with hpp-fcl but to ignore hpp-fcl in the Python bindings if the hpp-fcl Python bindings are not installed.
This create the following issues:
- To compute `BUILD_WITH_HPP_FCL_PYTHON_BINDINGS` we must call the Python interpreter. This create some issues when cross compiling.
- We never test this case in our CI, so we don't know if this option is working.
This PR remove this option to simplify the build.
In the case an user build Pinocchio Python binding with hpp-fcl C++ library but without hpp-fcl binding, the Python interpreter will raise an ImportError.
=> Always suppose hpp-fcl Python binding are present when hpp-fcl C++ library is found

CHANGELOG.md, include/pinocchio/algorithm/parallel/geometry.hpp, include/pinocchio/macros.hpp, include/pinocchio/math/casadi.hpp, include/pinocchio/math/cppad.hpp, include/pinocchio/math/cppadcg.hpp, include/pinocchio/parsers/sample-models.hpp, include/pinocchio/spatial/fcl-pinocchio-conversions.hpp, include/pinocchio/spatial/inertia.hpp
- Windows build fail when calling the PINOCCHIO_PRAGMA_DEPRECATED_HEADER macro that is not defined on Windows in macros.hpp.
- Fix DEPRECATED_HEADER messages that had been modified by clang-format.
- Fix ambiguous setZero call in InertiaTpl()
Another issue (not fixed right now) is the multiple definition of PINOCCHIO_DEPRECATED_HEADER and PINOCCHIO_PRAGMA in the jrl-cmakemodule generate deprecated.hpp.
We maybe have to use PINOCCHIO_PRAGMA from derpecated.hpp and change the name of our PINOCCHIO_DEPRECATED_HEADER definition that doesn't take the same number of argument than the one in deprecated.hpp.
=> Fix Windows build

CHANGELOG.md, include/pinocchio/algorithm/model.hxx, unittest/model.cpp
Solves [#2293 ](https://github.com/stack-of-tasks/pinocchio/issues/2293)
When joints at the base are in parallel, the transformation between modelA and modelB was applied only the first joint of the list, whereas it should be applied on all joints whose parent is the base of modelB.
=> [Model] Fix appendModel for parallel joints at the base

README.md
I wanted to add my project [PyRoboPlan](https://github.com/sea-bass/pyroboplan) to the README section describing open-source projects using Pinocchio.
THANK YOU, by the way. I've really enjoyed using this tool for the last ~7 months.
Also doing a drive-by change that updates my affiliation.
Hope this is OK.
=> Add PyRoboPlan to open-source projects

.pre-commit-config.yaml, CHANGELOG.md, include/pinocchio/bindings/python/multibody/geometry-object.hpp, include/pinocchio/bindings/python/multibody/joint/joints-models.hpp, include/pinocchio/multibody/joint/joint-helical.hpp, include/pinocchio/multibody/joint/joint-prismatic.hpp, include/pinocchio/multibody/joint/joint-revolute-unbounded.hpp, include/pinocchio/multibody/joint/joint-revolute.hpp
As discussed in https://github.com/stack-of-tasks/pinocchio/issues/2258, this pr changed the way the geometry material is parsed using eigenpy variant. 
It also adds a function to have an easy access to the joint axis for prismatic, revolute and helicoidal joints. https://github.com/stack-of-tasks/pinocchio/discussions/2196
=> Changed Geometry Objects bindings and added getMotionAxis function

.github/workflows/linux.yml
This PR changes the environment in which the Linux CI is run. Instead of using the github action environment, it is now run into a minimal docker container.
For more info, please see https://github.com/stack-of-tasks/pinocchio/issues/2253
=> CI - Change Environment for Linux CI

.github/workflows/linux.yml, CHANGELOG.md, CMakeLists.txt, unittest/packaging/pkgconfig/CMakeLists.txt
This PR add the following libraries into the pkg-config file (when built with the right option) :
- pinocchio_parsers
- pinocchio_collision
- pinocchio_extra
- pinocchio_casadi
- pinocchio_cppad
- pinocchio_cppadcg
Add missing defines.
=> Add missing dependencies into pkg-config

CHANGELOG.md, bindings/python/CMakeLists.txt
Hi,
This provide compatibility with older console_bridge versions.
This was not tested yet, so let's keep it as draft for now.
=> CMake: modernize link to console_bridge

CHANGELOG.md, bindings/python/pinocchio/robot_wrapper.py, bindings/python/pinocchio/visualize/meshcat_visualizer.py, examples/anymal-simulation.py, examples/meshcat-viewer-dae.py
=> Fix Dae support in MeshCat

CHANGELOG.md, CMakeLists.txt
CMake 3.30 don't package anymore the FindBoost.cmake file. Instead, it encourage to use the BoostModule.cmake distributed by Boost.
To avoid a warning message, we must set the CMP0167 policy to NEW.
Here the policy documentation:
> The FindBoost module is removed.
> CMake 3.29 and below provide a FindBoost module, but it needs constant
> updates to keep up with upstream Boost releases.  Upstream Boost 1.70
> and above provide a BoostConfig.cmake package configuration file.
> find_package(Boost CONFIG) finds the upstream package directly,
> without the find module.
> 
> CMake 3.30 and above prefer to not provide the FindBoost module
> so that find_package(Boost) calls, without the CONFIG or
> NO_MODULE options, find the upstream BoostConfig.cmake directly.
> This policy provides …
=> Set policy CMP0167 to avoid warnings with CMake 3.30

CHANGELOG.md, package.xml
The package.xml relies on liburdfdom-dev, which comes from Ubuntu instead of the one that comes from ROS 2. This usually leads to a situation where you have urdfdom installed twice on your system. Once from this package as liburdfdom-dev that is installed in `/usr/lib/x86_64-linux-gnu/` and once from other ROS 2  packages on your system that use the urdfdom from ROS 2 (like the urdf package), which is installed in `/opt/ros/{ROS_DISTRO}/lib/x86_64-linux-gnu`. This will now lead to [CMake warnings in other ROS 2 project that try to use urdfdom](https://github.com/Gauss-Robotics/xbot2_interface/pull/1#issuecomment-2238603609). It still works, but it might break in the future.
This PR changes the package.xml to rely on the urdfdom package that comes from ROS.
=> Fix urdfdom dependency

include/pinocchio/algorithm/constrained-dynamics.hpp, include/pinocchio/algorithm/proximal.hpp, include/pinocchio/bindings/python/algorithm/proximal.hpp
* Fix two equations that were not rendering correctly
* Fix typos: paramters → parameters
=> Fix two equations and typos in the documentation

CMakeLists.txt
Fix the error:
```
CMake Error at CMakeLists.txt:247 (if):
if given arguments:
"BUILD_WITH_URDF_SUPPORT" "AND" "VERSION_GREATER" "0.4.2"
Unknown arguments specified
```
when running `cmake -DBUILD_WITH_URDF_SUPPORT=off`
=> cmake - Fix cmake when urdf support is disabled.

doc/a-features/e-lie.md, doc/a-features/g-dynamic.md, doc/a-features/intro.md, doc/c-maths/a-rigid-bodies.md, doc/c-maths/b-joints.md, doc/c-maths/se3.md
I corrected typos and errors I found reading the docs : https://gepettoweb.laas.fr/doc/stack-of-tasks/pinocchio/master/doxygen-html/
Here are the less trivial ones, i.e. the ones I'm not totally sure about:
- in the intro, there is `where are the arguments...`. I added `arg1, arg2, ...`, and didn't include `model` and `data`.
- a SO(3) was used instead of SO(2).
- `\\( SO(3) \\)` is used in a title and render as is in chrome. I simply replaced with `SO(3)`
- I assume that "blocking of Cardan" refers to Gimbal Lock ?
- `the whole of all velocity vectors` means `the set of all velocity vectors` ?
- I think that a zero line is missing in the constraint matrix of the cylindrical joint.
=> doc: Fix typos and errors.

CHANGELOG.md, bindings/python/pinocchio/visualize/meshcat_visualizer.py
The proposal of this PR is to add a separate ``collision_color`` argument to `MeshcatVisualizer.loadViewerModel`.
- **Before:** `color` applies to both visual and collision model
- **After:** `color` applies to visual, `collision_color` to collision model
This can be convenient to debug collision meshes alongside the visual model (with only `color`, meshes overlapped):
```py
robot.setVisualizer(MeshcatVisualizer())
robot.initViewer(open=True)
robot.loadViewerModel(collision_color=(1.0, 0.0, 0.0, 0.3))
robot.viz.displayCollisions(True)
```
=> Separate collision_color in MeshcatVisualizer.loadViewerModel

CHANGELOG.md, bindings/python/pinocchio/robot_wrapper.py, unittest/python/CMakeLists.txt, unittest/python/robot_wrapper.py
This PR adds a ``BuildFromMJCF`` function to ``RobotWrapper``, following the same pattern as the existing ``BuildFromURDF`` and ``BuildFromSDF``. It was prompted by [this feature request](https://github.com/robot-descriptions/robot_descriptions.py/discussions/100).
=> Add BuildFromMJCF function to RobotWrapper

doc/d-practical-exercises/3-invkine.md
I think there's a missing `P_1` in the null-space projection formula in the "Inverse Kinematics" tutorial.
I did the math and it checks out. And the simulation works better.
=> doc - Correct null space projection formula.

.github/workflows/windows-conda.yml, CHANGELOG.md, CMakeLists.txt
On Windows, ensure proper handling of both cl.exe and clang-cl.exe. Previously, our setup did not use clang-cl.exe.
=> fix windows ci 

include/pinocchio/multibody/joint/joint-free-flyer.hpp
This PR starts documenting `JointModelFreeFlyerTpl`, with a focus on configuration and tangent coordinates.
=> doc: Document the JointModelFreeFlyerTpl structure

CHANGELOG.md, include/pinocchio/algorithm/contact-info.hpp
Hi,
This fix the symptoms described in #2304.
We should probably dig a bit more to find the cause.
Thanks a lot @jorisv for help there !
=> contact-info: cache nv, fix #2304

CHANGELOG.md, bindings/python/CMakeLists.txt, bindings/python/pinocchio/robot_wrapper.py, bindings/python/pinocchio/visualize/__init__.py, bindings/python/pinocchio/visualize/visualizers.py
Following #2331, the default viewer was updated from gepetto to meshcat.
This caused some troubles for users with gepetto set up and not meshcat.
This PR allows users to define their favorite viewer with the `PINOCCHIO_VIEWER` environment variable.
When it is not defined, the default viewer is automatically inferred from the available python modules.
=> configurable default visualizer

CHANGELOG.md, include/pinocchio/parsers/mjcf.hpp, include/pinocchio/parsers/mjcf/mjcf-graph.hpp, include/pinocchio/parsers/mjcf/model.hxx, src/parsers/mjcf/mjcf-graph.cpp, unittest/mjcf.cpp, unittest/models/closed_chain.xml, unittest/models/test_mjcf.xml
Hello Pinocchio Team,
While working with the `buildModel` function, I noticed that when an SDF description is passed, it directly produces a vector of `RigidConstraintModel`s. However, the `mjcf` format, which also supports closed-chain descriptions, currently does not parse the `equality/connect` tag.
To address this, I have added a draft implementation to enable parsing of the `equality/connect` tag in the `mjcf` format. I believe this enhancement will ease the work for people who use it.
Please feel free to review the draft implementation and share your feedback on its applicability to the Pinocchio library. I look forward to your comments!
Best regards,
Lev Kozlov
=> Feature: Support for Parsing MJCF `equality/connect` Tag for Closed Chains

CHANGELOG.md, include/pinocchio/bindings/python/spatial/force.hpp, include/pinocchio/bindings/python/spatial/inertia.hpp, include/pinocchio/bindings/python/spatial/motion.hpp, include/pinocchio/bindings/python/spatial/se3.hpp
Fix some issues with numpy2
- `__array__(self)` => `__array__(self, dtype=None, copy=None)`
=> Numpy 2 compatibility

README.md
Hi,
I think the CI workflow file for Windows was moved at some point, leaving a dangling URL pointer in the README.md status badge.
This PR fixes that.
=> [README] Fix the CI badge for the Windows workflow

CHANGELOG.md, CMakeLists.txt, bindings/python/parsers/python/model.cpp, include/pinocchio/bindings/python/parsers/python.hpp, include/pinocchio/parsers/python.hpp, sources.cmake, src/CMakeLists.txt, src/parsers/python/model.cpp, unittest/CMakeLists.txt, unittest/python_parser.cpp
=> Add pinocchio_python_parser target

CHANGELOG.md, include/pinocchio/parsers/mjcf/mjcf-graph.hpp, src/parsers/mjcf/mjcf-graph-geom.cpp, src/parsers/mjcf/mjcf-graph.cpp, unittest/mjcf.cpp
This pr aims at correcting parsing of armature parameter available in mjcf models. As of now, mjcf provided only one value per joint, but in pinocchio armature is based on the `model.nv`.
In this pr, we modify how armature is parsed and use the pinocchio standard.
Another aim of this pr is to add support for default tag that does not have a class name. Until now, this was taken into account in the mjcf parser.
=> Mjcf : Fix parsing of armature parameters

CHANGELOG.md, bindings/python/pinocchio/visualize/meshcat_visualizer.py
I got the following error while using the meshcat visualizer:
```
/root/miniforge3/lib/python3.12/site-packages/pinocchio/visualize/meshcat_visualizer.py:916: UserWarning: Error while loading geometry object: LThigh_0
Error message:
'str' object has no attribute 'is_absolute'
```
Therefore I forced the type to `Path`. This is coherent with the `Path(img_path_abs).open("rb")` two lines below.
=> meshcat_visualizer: force type of image paths to pathlib.Path

CHANGELOG.md, examples/append-urdf-model-with-another-model.py, examples/collision-with-point-clouds.py, examples/meshcat-viewer-octree.py, examples/meshcat-viewer-solo.py
This PR fix meshcat examples.
- `meshcat-viewer-octree.py` used deprecated API
- `meshcat-viewer-solo.py` used example_robot_data, but this package can't be imported in Pinocchio
Some meshact examples where broken, but also, some display nothing except 
- I had to add a sleep at the end of the script to display something on my browser. Is it normal @ManifoldFR ?
=> Fix meshcat examples

.github/workflows/update_pixi_lockfile.yml, CHANGELOG.md, examples/casadi/quadrotor-ocp.py, unittest/parallel-geometry.cpp
Fix some coal related issue:
- unittest/parallel-geometry.cpp fail because of this issue https://github.com/coal-library/coal/issues/636
Fix issue with quadrotor-ocp not convering on Windows:
- I can't reproduce on my computer, so it's skiped
=> Fix coal integration

CHANGELOG.md, bindings/python/pinocchio/visualize/meshcat_visualizer.py
=> Fix scaling support for meshcat

doc/d-practical-exercises/1-directgeom.md, doc/d-practical-exercises/2-invgeom.md, include/pinocchio/algorithm/geometry.hpp
Fix typo from `optionnal` to `optional`
=> fix: fix typo

.github/workflows/linux.yml, CHANGELOG.md, CMakeLists.txt, src/CMakeLists.txt
Add `PINOCCHIO_WITH_HPP_FCL` definiton on `pinocchio_default` target (when build with collision support) to build with core algorithms with collision support.
Draw back is if an user build pinocchio from sources with collision support but then want to build against `pinocchio_default` target without hpp-fcl/coal.
Bonus:
- Fix linux.yml CI
- Remove hpp-fcl from pkg-config file since hpp-fcl doesn't provide a .pc file
=> Activate collision specific features in pinocchio_default

CHANGELOG.md, include/pinocchio/parsers/mjcf/mjcf-graph.hpp, unittest/mjcf.cpp
This PR initializes `mapEulerAngles` with an identity matrix by default (matching MuJoCo's default 'xyz' sequence as documented in https://mujoco.readthedocs.io/en/stable/XMLreference.html#compiler-eulerseq).
While testing robots from https://github.com/google-deepmind/mujoco_menagerie, I encountered nan values in some frame transforms. After debugging, I found out that `mapEulerAngles` was not initialized by default and returned garbage values when no eulerseq was specified.
=> Mjcf: Use xyz as a default value for eulerseq compiler option

CHANGELOG.md, include/pinocchio/parsers/mjcf/mjcf-graph.hpp, src/parsers/mjcf/mjcf-graph-geom.cpp, src/parsers/mjcf/mjcf-graph.cpp, unittest/mjcf.cpp
This PR adds support for parsing MJCF meshes that are defined directly with vertices in the XML, rather than only supporting external mesh files. This makes it possible to load https://github.com/google-deepmind/mujoco/blob/main/model/car/car.xml and https://github.com/google-deepmind/mujoco/tree/main/model/cube
=> Add support for vertex-based mesh definitions in MJCF

CHANGELOG.md, bindings/python/CMakeLists.txt
Re-apply #1908 which was somehow forgotten during the v3 merge.
fix #2545
=> CMake: fix RPATH on macos

CHANGELOG.md, include/pinocchio/algorithm/aba.txx, include/pinocchio/parsers/mjcf/mjcf-graph.hpp, unittest/mjcf.cpp
I ran into `std::__ios_failure: basic_ios::clear: iostream error` errors while trying to parse [g1.xml](https://github.com/google-deepmind/mujoco_menagerie/blob/main/unitree_g1/g1.xml), after debugging it I found that it happens when parsing the keyframe's qpos attribute [here](https://github.com/google-deepmind/mujoco_menagerie/blob/main/unitree_g1/g1.xml#L347-L355).
This PR fixes it by changing the stream exception handling from failbit to badbit and simplifies vector parsing logic to better handle whitespace and newlines in MJCF files.
=> mjcf parser: Fix unknown size vector parsing

CHANGELOG.md, src/parsers/mjcf/mjcf-graph.cpp, unittest/mjcf.cpp
This PR addresses the issue with parsing sites in mjcf models, raised here https://github.com/stack-of-tasks/pinocchio/issues/2534. 
It also changes all the throw into pinocchio_pretty_throw.
=> Mjcf Parser : Fix adding the sites frames

CMakeLists.txt, doc/Doxyfile.extra.in
This PR follows the following two PRs on jrl-cmakemodules:
- https://github.com/jrl-umi3218/jrl-cmakemodules/pull/738
- https://github.com/jrl-umi3218/jrl-cmakemodules/pull/741
Local changes on Pinocchio include:
- removing the `DOXYGEN_USE_TEMPLATE_CSS` option which is irrelevant (removed in the first cmakemodules PR)
- removing the empty spec for `MATHJAX_RELPATH` which was wrong and broke the math
=> cmake : sync submodule + fix MathJax relpath, remove DOXYGEN_USE_TEMPLATE_CSS, remove MATHJAX_FORMAT spec

CHANGELOG.md, include/pinocchio/bindings/python/fwd.hpp, include/pinocchio/codegen/cppadcg.hpp, include/pinocchio/container/boost-container-limits.hpp, include/pinocchio/eigen-macros.hpp, include/pinocchio/math/multiprecision.hpp, include/pinocchio/multibody/liegroup/liegroup-base.hpp
since C++11 is already enforced in CMakeLists.txt
=> clean useless uses of PINOCCHIO_WITH_CXX11_SUPPORT

include/pinocchio/parsers/utils.hpp
Hi,
In https://github.com/Gepetto/example-robot-data/pull/265, we got:
```
ValueError: Schemes of formppackageare not handled
```
Which is a bit puzzling. Here is a trivial improvement.
=> parser: improve error message

CMakeLists.txt
Fix, at least on ROS buildfarm:
```
-- hpp-fcl FOUND. hpp-fcl at /opt/ros/rolling/lib/x86_64-linux-gnu/libhpp-fcl.so
-- Found Boost: /usr/include (found version "1.83.0") found components: chrono serialization filesystem
CMake Error at /opt/ros/rolling/lib/x86_64-linux-gnu/cmake/hpp-fcl/hpp-fclConfig.cmake:181 (message):
hpp-fcl: hpp-fcl >= 2.1.2 not found.
Call Stack (most recent call first):
cmake/package-config.cmake:133 (find_package)
CMakeLists.txt:341 (add_project_dependency)
```
=> CMake: fix for hpp-fcl/coal v3

CHANGELOG.md, include/pinocchio/autodiff/casadi/math/quaternion.hpp, include/pinocchio/autodiff/cppad/math/quaternion.hpp, include/pinocchio/bindings/python/spatial/explog.hpp, include/pinocchio/codegen/cppadcg.hpp, include/pinocchio/math/quaternion.hpp, include/pinocchio/multibody/data.hxx, include/pinocchio/multibody/joint/joint-basic-visitors.hxx, include/pinocchio/multibody/joint/joint-mimic.hpp, include/pinocchio/multibody/liegroup/special-euclidean.hpp, include/pinocchio/multibody/liegroup/special-orthogonal.hpp, src/parsers/mjcf/mjcf-graph-geom.cpp, unittest/all-joints.cpp, unittest/data.cpp, unittest/utils/model-generator.hpp
Dear Pinocchio folks,
As you know, I am working hard to support casting of multiple floating-point types as well as CppAD types in Crocoddyl. Currently, I have a draft version that needs to be reviewed before merging. However, there are changes in Pinocchio that prevent us from merging this new development, and I would very appreciate it if we can get them done quickly. Concretely, the needed changes are introduced in this PR, which can be summarized as:
1. Introduced a mechanism to change tolerance in quaternions. For instance, `1e-8` is not appropriate for float numbers and triggers issues during debug mode in Crocoddyl. In this PR, I propose using `1e-4` for float numbers, indeed. This code is also tested with CppAD types in Crocoddyl.
2. Fixed bug for casting `CppAD::cg::CG` scalars. …
=> Enhacing casting support for multiple floating-point scalars and Casadi and CppAD types

CHANGELOG.md, include/pinocchio/algorithm/contact-cholesky.hxx, include/pinocchio/algorithm/contact-jacobian.hxx
When cross-compiling, I get a link error that `ModelTpl::check()` is undefined : 
```bash
ld: src/libpinocchio_default.so.3.4.0: undefined reference to `pinocchio::ModelTpl<double, 0, pinocchio::JointCollectionDefaultTpl>::check(pinocchio::DataTpl<double, 0, pinocchio::JointCollectionDefaultTpl> const&) const'
```
Indeed the command `objdump` returns
```bash
❯ objdump -TC src/libpinocchio_default.so | grep check
0000000000000000      D  *UND*	0000000000000000  Base        pinocchio::ModelTpl<double, 0, pinocchio::JointCollectionDefaultTpl>::check(pinocchio::DataTpl<double, 0, pinocchio::JointCollectionDefaultTpl> const&) const
```
I don't know why I get this error when cross-compiling, and not with a native build. The fix I propose seems innocuous enough. It seems to be the right place to …
=> Fix ModelTpl::check() link

.github/workflows/linux.yml, .github/workflows/macos-linux-windows-pixi.yml, .github/workflows/ros_ci.yml, bindings/python/CMakeLists.txt, development/scripts/pixi/activation.bat, development/scripts/pixi/activation.sh, development/scripts/pixi/activation_clang.sh
- Fix ccache github cache key
- Fix ccache and pch compiler error with clang-cl
- Display ccache statistics
- Allow ccache to recognize conda compiler (compiler_type)
=> Fix PCH and ccache build

CHANGELOG.md, include/pinocchio/bindings/python/visualizers/visualizer-visitor.hpp
- **[python] visualizer-visitor : use lambdas to expose getters for models, data**
=> [python] Fix for getters in VisualizerPythonVisitor

include/pinocchio/bindings/python/visualizers/visualizer-visitor.hpp, unittest/python/CMakeLists.txt, unittest/python/bindings_visualizer.cpp, unittest/python/bindings_visualizer.py
- **unittest/python/CMakeLists.txt : add util function to create test C++ extension Python modules, and associated Python tests**
- **unittest/python : add test for visualizer bindings (visitor)**
=> unittest/python : add visualizer bindings visitor test, add CMake util to create C++ Python modules for tests
